
/**
 * ------------------------------------------------------------------
 * COPYRIGHT (c) 2026 ESTÚDIO CRIA
 * DIRETOR: PAULO GABRIEL DE L. S.
 * ------------------------------------------------------------------
 * 
 * BEM-VINDO AO DNA DO JOGO - VERSÃO "RECALIBRADA"
 * 
 * O Arquiteto ouviu seus gritos. A viscosidade do fluido foi aumentada.
 * Os inimigos agora se movem com a urgência de funcionários públicos.
 * 
 * EM TROCA: Os seus upgrades agora são menos potentes.
 * O equilíbrio deve ser mantido. Nada vem de graça.
 */

import { Upgrade, EntityType, WaveConfig, Language, Difficulty, Achievement, ThemePalette } from './types';

// --- PALETA DE CORES ---
export const COLORS_DEFAULT: ThemePalette = {
  BG: '#1a0505',
  PLAYER: '#ffffff',
  PLAYER_CORE: '#00ffff',
  BACTERIA: '#77dd77',
  VIRUS: '#00ff00', // AGORA VERDE (Como na imagem)
  PARASITE: '#ff3333',
  FUNGI: '#bf00ff', // AGORA ROXO (Antigo Virus)
  ENEMY_PROJECTILE: '#bf00ff', // ROXO TÓXICO
  BOSS: '#880000', 
  ELITE_GLOW: '#ffd700',
  ANTIBODY: '#00ffff',
  DNA: '#FFD700', // DOURADO (Moeda)
  BLOOD_PARTICLE: '#3a0a0a',
  UI_ACCENT: '#ff4444',
  SURGE: 'rgba(0, 255, 255, 0.3)',
  COMBO: '#ffaa00',
  ORBITAL: '#0088ff',
  BIO_MINE: '#ffaa00', // ATUALIZADO: ÂMBAR RADIOATIVO/DOURADO (Explosivo e Valioso)
  ACID_POOL: '#bf00ff' 
};

export const COLORS_PLATINUM: ThemePalette = {
  BG: '#0a0a1a', 
  PLAYER: '#ffffff',
  PLAYER_CORE: '#ffd700',
  BACTERIA: '#b39ddb', 
  VIRUS: '#c6ff00', // Verde Neon
  PARASITE: '#f48fb1', 
  FUNGI: '#80deea',
  ENEMY_PROJECTILE: '#bf00ff', 
  BOSS: '#ffd700', 
  ELITE_GLOW: '#ffffff', 
  ANTIBODY: '#ffd700',
  DNA: '#FFD700', 
  BLOOD_PARTICLE: '#1a1a2e', 
  UI_ACCENT: '#ffd700', 
  SURGE: 'rgba(255, 215, 0, 0.3)', 
  COMBO: '#ffffff',
  ORBITAL: '#ffd700',
  BIO_MINE: '#ff4500', // PLATINA: Laranja Neon Intenso
  ACID_POOL: '#7c4dff'
};

export const CANVAS_WIDTH = 1920;
export const CANVAS_HEIGHT = 1080;

// Configurações de Sobrevivência
export const INITIAL_LIVES = 3; 
export const ADRENALINE_MAX_DURATION = 20;

// Status iniciais do "Heroi". 
export const INITIAL_STATS = {
  speed: 4.5, // Leve aumento na velocidade base do player para compensar
  fireRate: 450, 
  damage: 15,
  bulletSpeed: 16, 
  bulletCount: 1,
  magnetRadius: 120, // Raio um pouco maior para ajudar na coleta
  maxHealth: 100, // Vida base restaurada para 100
  regen: 0, 
  maxEnergy: 100, // Energia base facilitada
  dashSpeed: 22, 
  dashCooldown: 1200, // Dash volta mais rápido
  critChance: 0.05, // 5% base
  critMultiplier: 1.5,
  orbitals: 0,
  thorns: 0,
  lifesteal: 0,
  dashDamage: 0,
  surgeRadiusMult: 1.0
};

// Multiplicadores de dificuldade.
// ATUALIZAÇÃO DO ARQUITETO: Dano maciço, velocidade controlada.
export const DIFFICULTY_MODIFIERS = {
  // TRIAGE (Fácil): Facilitado levemente
  [Difficulty.EASY]: { hp: 0.7, dmg: 0.7, speed: 0.55, score: 0.8 }, 
  
  // RESIDENT (Normal): Mantido original
  [Difficulty.NORMAL]: { hp: 1.5, dmg: 1.5, speed: 0.85, score: 1.0 }, 
  
  // SPECIALIST (Difícil): Levemente aumentado
  [Difficulty.HARD]: { hp: 3.0, dmg: 3.5, speed: 1.0, score: 1.5 }, 
  
  // APEX (Pesadelo): Aumentado a brutalidade
  [Difficulty.APEX]: { hp: 6.0, dmg: 7.0, speed: 1.25, score: 3.0 } 
};

export const PATIENT_NAMES_FIRST = ["J.", "A.", "M.", "K.", "R.", "S.", "T.", "L.", "C.", "B."];
export const PATIENT_NAMES_LAST = ["Doe", "Smith", "Neo", "Kovac", "Vane", "Ross", "Cole", "Drake", "Pike", "Ward"];

export const SYMPTOMS_KEYS = [
  "SYMPTOM_SEPTIC", "SYMPTOM_VIRAL", "SYMPTOM_NECROTIC", "SYMPTOM_CYTOKINE", 
  "SYMPTOM_FAILURE", "SYMPTOM_TOXICITY", "SYMPTOM_DECAY", "SYMPTOM_MUTATION"
];

export const ACHIEVEMENTS_LIST: Achievement[] = [
    { id: 'kill_100', icon: '🦠', titleKey: 'ACH_KILL_100_TITLE', descKey: 'ACH_KILL_100_DESC', targetValue: 100, isCumulative: true },
    { id: 'kill_1000', icon: '🧹', titleKey: 'ACH_KILL_1000_TITLE', descKey: 'ACH_KILL_1000_DESC', targetValue: 1000, isCumulative: true },
    { id: 'kill_5000', icon: '🔥', titleKey: 'ACH_KILL_5000_TITLE', descKey: 'ACH_KILL_5000_DESC', targetValue: 5000, isCumulative: true },
    { id: 'kill_10000', icon: '💀', titleKey: 'ACH_KILL_10000_TITLE', descKey: 'ACH_KILL_10000_DESC', targetValue: 10000, isCumulative: true },
    { id: 'boss_1', icon: '👾', titleKey: 'ACH_BOSS_1_TITLE', descKey: 'ACH_BOSS_1_DESC', targetValue: 1, isCumulative: true },
    { id: 'boss_10', icon: '👹', titleKey: 'ACH_BOSS_10_TITLE', descKey: 'ACH_BOSS_10_DESC', targetValue: 10, isCumulative: true },
    { id: 'boss_50', icon: '👑', titleKey: 'ACH_BOSS_50_TITLE', descKey: 'ACH_BOSS_50_DESC', targetValue: 50, isCumulative: true },
    { id: 'dash_kill_50', icon: '⚡', titleKey: 'ACH_DASH_KILL_50_TITLE', descKey: 'ACH_DASH_KILL_50_DESC', targetValue: 50, isCumulative: true },
    { id: 'surge_kill_100', icon: '🌊', titleKey: 'ACH_SURGE_KILL_100_TITLE', descKey: 'ACH_SURGE_KILL_100_DESC', targetValue: 100, isCumulative: true },
    { id: 'mine_pop_20', icon: '💣', titleKey: 'ACH_MINE_POP_20_TITLE', descKey: 'ACH_MINE_POP_20_DESC', targetValue: 20, isCumulative: true },
    { id: 'biomass_10k', icon: '💎', titleKey: 'ACH_BIOMASS_10K_TITLE', descKey: 'ACH_BIOMASS_10K_DESC', targetValue: 10000, isCumulative: true },
    { id: 'wave_5', icon: '🖐', titleKey: 'ACH_WAVE_5_TITLE', descKey: 'ACH_WAVE_5_DESC', targetValue: 5, isCumulative: false },
    { id: 'wave_10', icon: '🧗', titleKey: 'ACH_WAVE_10_TITLE', descKey: 'ACH_WAVE_10_DESC', targetValue: 10, isCumulative: false },
    { id: 'score_50k', icon: '📈', titleKey: 'ACH_SCORE_50K_TITLE', descKey: 'ACH_SCORE_50K_DESC', targetValue: 50000, isCumulative: false },
    { id: 'combo_50', icon: '⛓', titleKey: 'ACH_COMBO_50_TITLE', descKey: 'ACH_COMBO_50_DESC', targetValue: 50, isCumulative: false },
    { id: 'max_hp_200', icon: '❤️', titleKey: 'ACH_MAX_HP_200_TITLE', descKey: 'ACH_MAX_HP_200_DESC', targetValue: 200, isCumulative: false },
    { id: 'fire_rate_max', icon: '🔫', titleKey: 'ACH_FIRE_RATE_MAX_TITLE', descKey: 'ACH_FIRE_RATE_MAX_DESC', targetValue: 1, isCumulative: false },
    { id: 'perfect_wave', icon: '✨', titleKey: 'ACH_PERFECT_WAVE_TITLE', descKey: 'ACH_PERFECT_WAVE_DESC', targetValue: 1, isCumulative: true },
    { id: 'low_hp_survive', icon: '🚑', titleKey: 'ACH_LOW_HP_SURVIVE_TITLE', descKey: 'ACH_LOW_HP_SURVIVE_DESC', targetValue: 1, isCumulative: true },
    { id: 'crit_master', icon: '🎯', titleKey: 'ACH_CRIT_MASTER_TITLE', descKey: 'ACH_CRIT_MASTER_DESC', targetValue: 1000, isCumulative: true },
    { id: 'unlock_all_upgrades', icon: '🧬', titleKey: 'ACH_UNLOCK_ALL_TITLE', descKey: 'ACH_UNLOCK_ALL_DESC', targetValue: 12, isCumulative: true },
    { id: 'win_apex', icon: '🏆', titleKey: 'ACH_WIN_APEX_TITLE', descKey: 'ACH_WIN_APEX_DESC', targetValue: 1, isCumulative: false },
    { id: 'die_10', icon: '⚰️', titleKey: 'ACH_DIE_10_TITLE', descKey: 'ACH_DIE_10_DESC', targetValue: 10, isCumulative: true },
    { id: 'afk', icon: '🗿', titleKey: 'ACH_AFK_TITLE', descKey: 'ACH_AFK_DESC', targetValue: 10, isCumulative: false, secret: true },
    { id: 'pacifist', icon: '🕊', titleKey: 'ACH_PACIFIST_TITLE', descKey: 'ACH_PACIFIST_DESC', targetValue: 30, isCumulative: false, secret: true },
    { id: 'overkill', icon: '💥', titleKey: 'ACH_OVERKILL_TITLE', descKey: 'ACH_OVERKILL_DESC', targetValue: 1, isCumulative: true },
    { id: 'rich', icon: '💰', titleKey: 'ACH_RICH_TITLE', descKey: 'ACH_RICH_DESC', targetValue: 3000, isCumulative: false },
    { id: 'play_time_1h', icon: '⏳', titleKey: 'ACH_PLAY_TIME_1H_TITLE', descKey: 'ACH_PLAY_TIME_1H_DESC', targetValue: 3600, isCumulative: true },
    { id: 'play_time_5h', icon: '👨‍⚕️', titleKey: 'ACH_PLAY_TIME_5H_TITLE', descKey: 'ACH_PLAY_TIME_5H_DESC', targetValue: 18000, isCumulative: true },
    { id: 'all_achievements', icon: '💠', titleKey: 'ACH_ALL_TITLE', descKey: 'ACH_ALL_DESC', targetValue: 1, isCumulative: true, secret: true }
];

type TranslationMap = {
  [key in Language]: {
    [key: string]: string;
  };
};

export const TEXTS: TranslationMap = {
  EN: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INJECT",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLS",
    MANUAL: "DATABASE",
    CREDITS: "CREDITS",
    LANG: "LANGUAGE",
    BACK: "RETURN",
    PAUSED: "SYSTEM PAUSED",
    RESUME: "RESUME",
    ABORT: "ABORT MISSION",
    GAME_OVER: "PATIENT LOST",
    RETRY: "NEXT PATIENT",
    WAVE: "WAVE",
    SCORE: "SCORE",
    CLEARED: "STABILIZED",
    NEXT: "NEXT SECTOR",
    MUTATION: "BIO-LAB",
    SELECT_DNA: "SPEND BIOMASS TO EVOLVE",
    SURGE_READY: "SURGE",
    DEPLOY: "DEPLOY",
    BRIEFING: "PATIENT CHART",
    BOSS_WARNING: "ANOMALY DETECTED",
    OPEN_SHOP: "OPEN BIO-LAB",
    PURCHASE: "EVOLVE",
    COST: "COST",
    MAXED: "MAX",
    COMBO: "COMBO",
    DASH: "DASH",
    DIFFICULTY: "RISK LEVEL",
    PATIENT: "SUBJECT",
    STRAIN: "STRAIN",
    BIOMASS_AVAIL: "BIOMASS AVAILABLE",
    AUDIO_LINK: "AUDIO LINK",
    STATUS_TERM: "STATUS: TERMINATED",
    INTEGRITY: "INTEGRITY",
    ADRENALINE: "ADRENALINA ACTIVE",
    LOADOUT: "ACTIVE GENOME",
    ACHIEVEMENTS: "ACHIEVEMENTS",
    ACH_LOCKED: "LOCKED",
    ACH_PROGRESS: "PROGRESS",
    ACH_PLATINUM_MSG: "SYSTEM OVERRIDE: APEX MODE ENGAGED. VISUALS EVOLVED.",
    DIFF_TRIAGE: "TRIAGE",
    DIFF_RESIDENT: "RESIDENT",
    DIFF_SPECIALIST: "SPECIALIST",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVEMENT",
    CTRL_MOVE_DESC: "WASD / ARROWS / TOUCH JOYSTICK",
    CTRL_DASH: "DASH / EVADE",
    CTRL_DASH_DESC: "SHIFT / E / TOUCH BUTTON",
    CTRL_SURGE: "SURGE ULTIMATE",
    CTRL_SURGE_DESC: "SPACE / TOUCH BUTTON",
    CTRL_NOTE: "AUTO-FIRE IS ALWAYS ENGAGED",
    MANUAL_HOSTILES: "HOSTILES",
    MANUAL_STRAINS: "VIRAL STRAINS",
    MANUAL_MECHANICS: "BATTLE MECHANICS",
    MANUAL_BAC_DESC: "Standard pathogen. Common, predictable movement.",
    MANUAL_VIR_DESC: "Stationary turret. Shoots tracking spikes.", // SWAPPED
    MANUAL_PAR_DESC: "Heavy tank. Slow, high HP, absorbs damage.",
    MANUAL_FUNGI_DESC: "Fast attacker. Erratic zig-zag movement.", // ALTERADO
    MANUAL_BOSS_DESC: "Massive anomaly. Requires extreme firepower.",
    MANUAL_MECH_DASH_TITLE: "Evasive Dash",
    MANUAL_MECH_DASH_DESC: "Grants momentary invulnerability. Use to pass through enemies.",
    MANUAL_MECH_SURGE_TITLE: "Surge System",
    MANUAL_MECH_SURGE_DESC: "Push enemies back and MAGNETIZE all biomass instantly.",
    MANUAL_MECH_COMBO_TITLE: "Combo Chain",
    MANUAL_MECH_COMBO_DESC: "Kill fast to increase score multiplier. Taking damage resets combo.",
    STRAIN_STANDARD: "STANDARD PATHOGEN",
    STRAIN_SWARM: "SWARM CLUSTER",
    STRAIN_TITAN: "ARMORED TITAN",
    STRAIN_VOLATILE: "VOLATILE MUTATION",
    STRAIN_STD_DESC: "Baseline infection parameters.",
    STRAIN_SWM_DESC: "High enemy count, lower individual HP.",
    STRAIN_TTN_DESC: "Enemies have +100% HP. Slower spawns.",
    STRAIN_VOL_DESC: "Enemies move 30% faster. High aggression.",
    ROLE_DEV: "DEVELOPMENT",
    ROLE_DIR: "DIRECTOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Septic Shock",
    SYMPTOM_VIRAL: "Unknown Viral Load",
    SYMPTOM_NECROTIC: "Necrotic Tissue",
    SYMPTOM_CYTOKINE: "Cytokine Storm",
    SYMPTOM_FAILURE: "Organ Failure",
    SYMPTOM_TOXICITY: "Blood Toxicity",
    SYMPTOM_DECAY: "Cellular Decay",
    SYMPTOM_MUTATION: "Rapid Mutation",
    // HUD & In-Game Text
    LABEL_SYMPTOMS: "SYMPTOMS",
    LABEL_ID: "ID",
    LABEL_AUDIO: "AUDIO",
    LABEL_OVERRIDE: "SYSTEM OVERRIDE",
    PH_ACCESS_CODE: "ACCESS CODE",
    MSG_SURGE: "SURGE!",
    MSG_ADRENALINE_EMPTY: "ADRENALINE DEPLETED!",
    MSG_BOSS_WARN: "WARNING: BOSS",
    MSG_COMBO_LOST: "COMBO LOST",
    MSG_RESTORED: "SYSTEM RESTORED",
    MSG_HP_PLUS: "+HP",
    MSG_BOOM: "BOOM!",
    MSG_COMBO_X: "COMBO!",
    NO_MUTATIONS: "NO ACTIVE MUTATIONS DETECTED",
    // Settings Keys
    AUDIO_PROTOCOLS: "AUDIO PROTOCOLS",
    MASTER_OUTPUT: "MASTER OUTPUT",
    MUSIC_STREAM: "MUSIC STREAM",
    SFX_FEEDBACK: "SFX FEEDBACK",
    VISUAL_OPTICS: "VISUAL OPTICS",
    RETRO_FILTER: "RETRO FILTER",
    CRT_DESC: "CRT SCANLINES & VIGNETTE",
    SYSTEM_PURGE: "SYSTEM PURGE (RESET DATA)",
    CONFIRM_PURGE: "⚠️ CONFIRM PURGE? ⚠️",
    HIGH_QUALITY: "FORCE HIGH QUALITY",
    HQ_WARNING: "WARNING: Disabling performance mode may cause severe lag on this device.",
    // Upgrades
    UP_MITOSIS_NAME: "RAPID MITOSIS",
    UP_MITOSIS_DESC: "+6% Fire Rate",
    UP_MEMBRANE_NAME: "TITANIUM MEMBRANE",
    UP_MEMBRANE_DESC: "+12% Max HP & Full Heal",
    UP_ENZYME_NAME: "HYPER ENZYMES",
    UP_ENZYME_DESC: "+8% Damage",
    UP_MULTISHOT_NAME: "ADAPTIVE SPLIT",
    UP_MULTISHOT_DESC: "+1 Projectile, -25% Damage",
    UP_ENERGY_NAME: "MITOCHONDRIA BOOST",
    UP_ENERGY_DESC: "Surge & Dash recharge 8% faster",
    UP_GIGA_NAME: "CYTOKINE STORM",
    UP_GIGA_DESC: "+1 Proj, +20% Dmg, Full Heal", 
    UP_ORBITAL_NAME: "NANO-GUARDIANS",
    UP_ORBITAL_DESC: "Adds +1 Autonomous Defensive Drone",
    UP_DASH_NAME: "PLASMA TRAIL",
    UP_DASH_DESC: "Dash deals 15 Damage to enemies passed",
    UP_CRIT_NAME: "PRECISION OPTICS",
    UP_CRIT_DESC: "+4% Crit Chance, +0.15x Crit Dmg",
    UP_THORNS_NAME: "SPIKED CARAPACE",
    UP_THORNS_DESC: "Deals 1.5 Contact Dmg to attackers",
    UP_LIFE_NAME: "VAMPIRIC STRAIN",
    UP_LIFE_DESC: "Crit kills heal +1 HP",
    UP_MAGNET_NAME: "MAGNETIC FIELD",
    UP_MAGNET_DESC: "+10% Magnet Range & Surge Radius",
    // Achievements
    ACH_KILL_100_TITLE: "Cleaner",
    ACH_KILL_100_DESC: "Eliminate 100 pathogens.",
    ACH_KILL_1000_TITLE: "Sterilizer",
    ACH_KILL_1000_DESC: "Eliminate 1,000 pathogens.",
    ACH_KILL_5000_TITLE: "Eradicator",
    ACH_KILL_5000_DESC: "Eliminate 5,000 pathogens.",
    ACH_KILL_10000_TITLE: "Extinction Event",
    ACH_KILL_10000_DESC: "Eliminate 10,000 pathogens.",
    ACH_BOSS_1_TITLE: "Anomaly Neutralized",
    ACH_BOSS_1_DESC: "Defeat your first Boss.",
    ACH_BOSS_10_TITLE: "Titan Slayer",
    ACH_BOSS_10_DESC: "Defeat 10 Bosses.",
    ACH_BOSS_50_TITLE: "King of Veins",
    ACH_BOSS_50_DESC: "Defeat 50 Bosses.",
    ACH_DASH_KILL_50_TITLE: "Roadkill",
    ACH_DASH_KILL_50_DESC: "Kill 50 enemies using Dash damage.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Kill 100 enemies with Surge blasts.",
    ACH_MINE_POP_20_TITLE: "Minesweeper",
    ACH_MINE_POP_20_DESC: "Detonate 20 Bio-Minas.",
    ACH_BIOMASS_10K_TITLE: "Hoarder",
    ACH_BIOMASS_10K_DESC: "Collect 10,000 total Biomass.",
    ACH_WAVE_5_TITLE: "Survivor",
    ACH_WAVE_5_DESC: "Reach Wave 5.",
    ACH_WAVE_10_TITLE: "Deep Dive",
    ACH_WAVE_10_DESC: "Reach Wave 10 (Endless Mode).",
    ACH_SCORE_50K_TITLE: "High Score",
    ACH_SCORE_50K_DESC: "Reach 50,000 Score in one run.",
    ACH_COMBO_50_TITLE: "Flow State",
    ACH_COMBO_50_DESC: "Reach a 50x Combo.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Reach 200 Max HP in a run.",
    ACH_FIRE_RATE_MAX_TITLE: "Minigun",
    ACH_FIRE_RATE_MAX_DESC: "Max out Fire Rate upgrade.",
    ACH_PERFECT_WAVE_TITLE: "Untouchable",
    ACH_PERFECT_WAVE_DESC: "Complete a wave without taking damage.",
    ACH_LOW_HP_SURVIVE_TITLE: "Adrenaline Junkie",
    ACH_LOW_HP_SURVIVE_DESC: "Clear a wave with < 20% HP.",
    ACH_CRIT_MASTER_TITLE: "Surgical Precision",
    ACH_CRIT_MASTER_DESC: "Land 1,000 Critical Hits.",
    ACH_UNLOCK_ALL_TITLE: "Genetic Perfection",
    ACH_UNLOCK_ALL_DESC: "Buy every type of upgrade at least once (Cumulative).",
    ACH_WIN_APEX_TITLE: "Apex Predator",
    ACH_WIN_APEX_DESC: "Clear Wave 5 on APEX difficulty.",
    ACH_DIE_10_TITLE: "Trial and Error",
    ACH_DIE_10_DESC: "Die 10 times.",
    ACH_AFK_TITLE: "Statue",
    ACH_AFK_DESC: "Stand still for 10 seconds in combat.",
    ACH_PACIFIST_TITLE: "Pacifist",
    ACH_PACIFIST_DESC: "Survive 30 seconds without shooting.",
    ACH_OVERKILL_TITLE: "Overkill",
    ACH_OVERKILL_DESC: "Deal over 500 damage in a single hit.",
    ACH_RICH_TITLE: "Tycoon",
    ACH_RICH_DESC: "Hold 3,000 Biomass at once.",
    ACH_PLAY_TIME_1H_TITLE: "Intern",
    ACH_PLAY_TIME_1H_DESC: "Play for 1 hour (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Specialist",
    ACH_PLAY_TIME_5H_DESC: "Play for 5 hours (Total).",
    ACH_ALL_TITLE: "THE APEX VIRUS",
    ACH_ALL_DESC: "Unlock all other achievements."
  },
  PT: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INJETAR",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLES",
    MANUAL: "BANCO DE DADOS",
    CREDITS: "CRÉDITOS",
    LANG: "IDIOMA",
    BACK: "VOLTAR",
    PAUSED: "SISTEMA PAUSADO",
    RESUME: "RETOMAR",
    ABORT: "ABORTAR MISSÃO",
    GAME_OVER: "PACIENTE PERDIDO",
    RETRY: "PRÓXIMO PACIENTE",
    WAVE: "ONDA",
    SCORE: "PONTOS",
    CLEARED: "ESTABILIZADO",
    NEXT: "PRÓXIMO SETOR",
    MUTATION: "BIO-LABORATÓRIO",
    SELECT_DNA: "GASTAR BIOMASSA PARA EVOLUIR",
    SURGE_READY: "SURTO",
    DEPLOY: "IMPLANTAR",
    BRIEFING: "PRONTUÁRIO",
    BOSS_WARNING: "ANOMALIA DETECTADA",
    OPEN_SHOP: "ABRIR BIO-LAB",
    PURCHASE: "EVOLUIR",
    COST: "CUSTO",
    MAXED: "MÁX",
    COMBO: "COMBO",
    DASH: "ESQUIVA",
    DIFFICULTY: "NÍVEL DE RISCO",
    PATIENT: "SUJEITO",
    STRAIN: "CEPA",
    BIOMASS_AVAIL: "BIOMASSA DISPONÍVEL",
    AUDIO_LINK: "LINK DE ÁUDIO",
    STATUS_TERM: "STATUS: TERMINADO",
    INTEGRITY: "INTEGRIDADE",
    ADRENALINE: "ADRENALINA ATIVA",
    LOADOUT: "GENOMA ATIVO",
    ACHIEVEMENTS: "CONQUISTAS",
    ACH_LOCKED: "BLOQUEADO",
    ACH_PROGRESS: "PROGRESSO",
    ACH_PLATINUM_MSG: "SOBREPOSIÇÃO DE SISTEMA: MODO APEX ATIVADO. VISUALES EVOLUÍDOS.",
    DIFF_TRIAGE: "TRIAGEM",
    DIFF_RESIDENT: "RESIDENTE",
    DIFF_SPECIALIST: "ESPECIALISTA",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVIMENTO",
    CTRL_MOVE_DESC: "WASD / SETAS / JOYSTICK NA TELA",
    CTRL_DASH: "ESQUIVA RÁPIDA",
    CTRL_DASH_DESC: "SHIFT / E / BOTÃO NA TELA",
    CTRL_SURGE: "SURTO SUPREMO",
    CTRL_SURGE_DESC: "ESPAÇO / BOTÃO NA TELA",
    CTRL_NOTE: "DISPARO AUTOMÁTICO SEMPRE ATIVO",
    MANUAL_HOSTILES: "HOSTIS",
    MANUAL_STRAINS: "CEPAS VIRAIS",
    MANUAL_MECHANICS: "MECÂNICAS DE COMBATE",
    MANUAL_BAC_DESC: "Patógeno padrão. Movimento comum e previsível.",
    MANUAL_VIR_DESC: "Torreta estacionária. Dispara espinas teledirigidas.", // SWAPPED
    MANUAL_PAR_DESC: "Tanque pesado. Lento, muita vida, absorve dano.",
    MANUAL_FUNGI_DESC: "Atacante rápido. Movimento errático em zigue-zague.", // ALTERADO
    MANUAL_BOSS_DESC: "Anomalia massiva. Requer poder de fogo extremo.",
    MANUAL_MECH_DASH_TITLE: "Esquiva (Dash)",
    MANUAL_MECH_DASH_DESC: "Concede invulnerabilidade momentânea. Use para atravessar inimigos.",
    MANUAL_MECH_SURGE_TITLE: "Sistema de Surto",
    MANUAL_MECH_SURGE_DESC: "Empurra inimigos e MAGNETIZA toda biomassa instantaneamente.",
    MANUAL_MECH_COMBO_TITLE: "Corrente de Combo",
    MANUAL_MECH_COMBO_DESC: "Mate rápido para aumentar multiplicador. Levar dano zera o combo.",
    STRAIN_STANDARD: "PATÓGENO PADRÃO",
    STRAIN_SWARM: "ENXAME MASSIVO",
    STRAIN_TITAN: "TITÃ BLINDADO",
    STRAIN_VOLATILE: "MUTAÇÃO VOLÁTIL",
    STRAIN_STD_DESC: "Parâmetros de infecção basais.",
    STRAIN_SWM_DESC: "Alto número de inimigos, menos vida individual.",
    STRAIN_TTN_DESC: "Inimigos com +100% Vida. Spawns mais lentos.",
    STRAIN_VOL_DESC: "Inimigos movem 30% mais rápido. Alta agressão.",
    ROLE_DEV: "DESENVOLVIMENTO",
    ROLE_DIR: "DIRETOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Choque Séptico",
    SYMPTOM_VIRAL: "Carga Viral Desconhecida",
    SYMPTOM_NECROTIC: "Tecido Necrótico",
    SYMPTOM_CYTOKINE: "Tempestade de Citocina",
    SYMPTOM_FAILURE: "Falência de Órgãos",
    SYMPTOM_TOXICITY: "Toxicidade Sanguínea",
    SYMPTOM_DECAY: "Decaimento Celular",
    SYMPTOM_MUTATION: "Mutação Rápida",
    // HUD & In-Game Text
    LABEL_SYMPTOMS: "SINTOMAS",
    LABEL_ID: "ID",
    LABEL_AUDIO: "ÁUDIO",
    LABEL_OVERRIDE: "SOBREPOSIÇÃO DE SISTEMA",
    PH_ACCESS_CODE: "CÓDIGO DE ACESSO",
    MSG_SURGE: "SURTO!",
    MSG_ADRENALINE_EMPTY: "ADRENALINA ESGOTADA!",
    MSG_BOSS_WARN: "ALERTA: BOSS",
    MSG_COMBO_LOST: "COMBO PERDIDO",
    MSG_RESTORED: "SISTEMA RESTAURADO",
    MSG_HP_PLUS: "+VIDA",
    MSG_BOOM: "BOOM!",
    MSG_COMBO_X: "COMBO!",
    NO_MUTATIONS: "NENHUMA MUTAÇÃO ATIVA DETECTADA",
    // Settings Keys
    AUDIO_PROTOCOLS: "PROTOCOLOS DE ÁUDIO",
    MASTER_OUTPUT: "VOLUME GERAL",
    MUSIC_STREAM: "MÚSICA",
    SFX_FEEDBACK: "EFEITOS (SFX)",
    VISUAL_OPTICS: "ÓPTICA VISUAL",
    RETRO_FILTER: "FILTRO RETRÔ",
    CRT_DESC: "SCANLINES & VINHETA",
    SYSTEM_PURGE: "PURGAR SISTEMA (APAGAR)",
    CONFIRM_PURGE: "⚠️ CONFIRMAR PURGA? ⚠️",
    HIGH_QUALITY: "FORÇAR ALTA QUALIDADE",
    HQ_WARNING: "AVISO: Desativar o modo desempenho pode causar lentidão severa neste dispositivo.",
    // Upgrades
    UP_MITOSIS_NAME: "MITOSE RÁPIDA",
    UP_MITOSIS_DESC: "+6% Cadência de Tiro",
    UP_MEMBRANE_NAME: "MEMBRANA DE TITÂNIO",
    UP_MEMBRANE_DESC: "+12% Vida Máx & Cura Total",
    UP_ENZYME_NAME: "HIPER ENZIMAS",
    UP_ENZYME_DESC: "+8% Dano",
    UP_MULTISHOT_NAME: "DIVISÃO ADAPTATIVA",
    UP_MULTISHOT_DESC: "+1 Projétil, -25% Dano",
    UP_ENERGY_NAME: "IMPULSO MITOCONDRIAL",
    UP_ENERGY_DESC: "Surto e Esquiva recarregam 8% mais rápido",
    UP_GIGA_NAME: "TEMPESTADE CITOCINA",
    UP_GIGA_DESC: "+1 Proj, +20% Dano, Cura Total", 
    UP_ORBITAL_NAME: "NANO-GUARDIÕES",
    UP_ORBITAL_DESC: "Adiciona +1 Drone de Defesa Autônomo",
    UP_DASH_NAME: "RASTRO DE PLASMA",
    UP_DASH_DESC: "Dash causa 15 de Dano ao atravesar inimigos",
    UP_CRIT_NAME: "ÓPTICA DE PRECISÃO",
    UP_CRIT_DESC: "+4% Chance Crítica, +0.15x Dano Crítico",
    UP_THORNS_NAME: "CARAPAÇA DE ESPINHOS",
    UP_THORNS_DESC: "Causa 1.5 de Dano ao ser tocado",
    UP_LIFE_NAME: "CEPA VAMPÍRICA",
    UP_LIFE_DESC: "Abates críticos curam +1 Vida",
    UP_MAGNET_NAME: "CAMPO MAGNÉTICO",
    UP_MAGNET_DESC: "+10% Alcance do Ímã e Tamanho do Surto",
    // Achievements
    ACH_KILL_100_TITLE: "Dedetizador",
    ACH_KILL_100_DESC: "Elimine 100 patógenos.",
    ACH_KILL_1000_TITLE: "Esterilizador",
    ACH_KILL_1000_DESC: "Elimine 1.000 patógenos.",
    ACH_KILL_5000_TITLE: "Erradicador",
    ACH_KILL_5000_DESC: "Elimine 5.000 patógenos.",
    ACH_KILL_10000_TITLE: "Evento de Extinção",
    ACH_KILL_10000_DESC: "Elimine 10.000 patógenos.",
    ACH_BOSS_1_TITLE: "Anomalia Neutralizada",
    ACH_BOSS_1_DESC: "Derrote seu primeiro Boss.",
    ACH_BOSS_10_TITLE: "Matador de Titãs",
    ACH_BOSS_10_DESC: "Derrote 10 Bosses.",
    ACH_BOSS_50_TITLE: "Rei das Veias",
    ACH_BOSS_50_DESC: "Derrote 50 Bosses.",
    ACH_DASH_KILL_50_TITLE: "Atropelamento",
    ACH_DASH_KILL_50_DESC: "Mate 50 inimigos usando o dano do Dash.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Mate 100 inimigos com a explosão do Surto.",
    ACH_MINE_POP_20_TITLE: "Campo Minado",
    ACH_MINE_POP_20_DESC: "Detone 20 Bio-Minas.",
    ACH_BIOMASS_10K_TITLE: "Acumulador",
    ACH_BIOMASS_10K_DESC: "Colete um total de 10.000 de Biomassa.",
    ACH_WAVE_5_TITLE: "Sobrevivente",
    ACH_WAVE_5_DESC: "Chegue à Onda 5.",
    ACH_WAVE_10_TITLE: "Mergulho Profundo",
    ACH_WAVE_10_DESC: "Chegue à Onda 10 (Modo Infinito).",
    ACH_SCORE_50K_TITLE: "Recordista",
    ACH_SCORE_50K_DESC: "Alcance 50.000 pontos em uma partida.",
    ACH_COMBO_50_TITLE: "Estado de Fluxo",
    ACH_COMBO_50_DESC: "Alcance um Combo de 50x.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Alcance 200 de Vida Máxima em uma partida.",
    ACH_FIRE_RATE_MAX_TITLE: "Metralhadora",
    ACH_FIRE_RATE_MAX_DESC: "Maximize o upgrade de Cadência de Tiro.",
    ACH_PERFECT_WAVE_TITLE: "Intocável",
    ACH_PERFECT_WAVE_DESC: "Complete uma onda sem levar dano.",
    ACH_LOW_HP_SURVIVE_TITLE: "Viciado em Adrenalina",
    ACH_LOW_HP_SURVIVE_DESC: "Vença uma onda com < 20% de Vida.",
    ACH_CRIT_MASTER_TITLE: "Precisão Cirúrgica",
    ACH_CRIT_MASTER_DESC: "Acerte 1.000 Críticos.",
    ACH_UNLOCK_ALL_TITLE: "Perfeição Genética",
    ACH_UNLOCK_ALL_DESC: "Compre todos os tipos de upgrade pelo menos uma vez.",
    ACH_WIN_APEX_TITLE: "Predador Apex",
    ACH_WIN_APEX_DESC: "Complete a Onda 5 na dificuldade APEX.",
    ACH_DIE_10_TITLE: "Tentativa e Erro",
    ACH_DIE_10_DESC: "Morra 10 vezes.",
    ACH_AFK_TITLE: "Estátua",
    ACH_AFK_DESC: "Fique parado por 10 segundos em combate.",
    ACH_PACIFIST_TITLE: "Pacifista",
    ACH_PACIFIST_DESC: "Sobreviva 30 segundos sem atirar.",
    ACH_OVERKILL_TITLE: "Exagero",
    ACH_OVERKILL_DESC: "Cause mais de 500 de dano em um único hit.",
    ACH_RICH_TITLE: "Magnata",
    ACH_RICH_DESC: "Tenha 3.000 de Biomassa ao mesmo tempo.",
    ACH_PLAY_TIME_1H_TITLE: "Estagiário",
    ACH_PLAY_TIME_1H_DESC: "Jogue por 1 hora (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Especialista",
    ACH_PLAY_TIME_5H_DESC: "Jogue por 5 horas (Total).",
    ACH_ALL_TITLE: "O VÍRUS APEX",
    ACH_ALL_DESC: "Desbloqueie todas as outras conquistas."
  },
  ES: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INYECTAR",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLES",
    MANUAL: "BASE DE DATOS",
    CREDITS: "CRÉDITOS",
    LANG: "IDIOMA",
    BACK: "VOLVER",
    PAUSED: "SISTEMA PAUSADO",
    RESUME: "REANUDAR",
    ABORT: "ABORTAR MISIÓN",
    GAME_OVER: "PACIENTE PERDIDO",
    RETRY: "SIGUIENTE PACIENTE",
    WAVE: "OLEADA",
    SCORE: "PUNTUACIÓN",
    CLEARED: "ESTABILIZADO",
    NEXT: "PRÓXIMO SECTOR",
    MUTATION: "BIO-LABORATORIO",
    SELECT_DNA: "GASTAR BIOMASA PARA EVOLUCIONAR",
    SURGE_READY: "SURGE",
    DEPLOY: "DESPLEGAR",
    BRIEFING: "EXPEDIENTE",
    BOSS_WARNING: "ANOMALÍA DETECTADA",
    OPEN_SHOP: "ABRIR BIO-LAB",
    PURCHASE: "EVOLUCIONAR",
    COST: "COSTO",
    MAXED: "MÁX",
    COMBO: "COMBO",
    DASH: "ESQUIVA",
    DIFFICULTY: "NIVEL DE RIESGO",
    PATIENT: "SUJETO",
    STRAIN: "CEPA",
    BIOMASS_AVAIL: "BIOMASA DISPONIBLE",
    AUDIO_LINK: "ENLACE DE AUDIO",
    STATUS_TERM: "ESTADO: TERMINADO",
    INTEGRITY: "INTEGRIDAD",
    ADRENALINE: "ADRENALINA ACTIVA",
    LOADOUT: "GENOMA ACTIVO",
    ACHIEVEMENTS: "LOGROS",
    ACH_LOCKED: "BLOQUEADO",
    ACH_PROGRESS: "PROGRESO",
    ACH_PLATINUM_MSG: "ANULACIÓN DEL SISTEMA: MODO APEX ACTIVADO. VISUALES EVOLUCIONADOS.",
    DIFF_TRIAGE: "TRIAJE",
    DIFF_RESIDENT: "RESIDENTE",
    DIFF_SPECIALIST: "ESPECIALISTA",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVIMENTO",
    CTRL_MOVE_DESC: "WASD / FLECHAS / JOYSTICK TÁCTIL",
    CTRL_DASH: "ESQUIVA",
    CTRL_DASH_DESC: "SHIFT / E / BOTÓN TÁCTIL",
    CTRL_SURGE: "SURGE DEFINITIVA",
    CTRL_SURGE_DESC: "ESPACIO / BOTÓN TÁCTIL",
    CTRL_NOTE: "DISPARO AUTOMÁTICO SIEMPRE ACTIVO",
    MANUAL_HOSTILES: "HOSTILES",
    MANUAL_STRAINS: "CEPAS VIRALES",
    MANUAL_MECHANICS: "MECÁNICA DE BATALLA",
    MANUAL_BAC_DESC: "Patógeno estándar. Movimiento común y predecible.",
    MANUAL_VIR_DESC: "Torreta estacionaria. Dispara espinas teledirigidas.", // SWAPPED
    MANUAL_PAR_DESC: "Tanque pesado. Lento, mucha vida, absorve daño.",
    MANUAL_FUNGI_DESC: "Atacante rápido. Movimiento errático en zig-zag.", // ALTERADO
    MANUAL_BOSS_DESC: "Anomalia masiva. Requiere potencia de fuego extrema.",
    MANUAL_MECH_DASH_TITLE: "Evasión (Dash)",
    MANUAL_MECH_DASH_DESC: "Otorga invulnerabilidade momentánea. Úsalo para atravesar enemigos.",
    MANUAL_MECH_SURGE_TITLE: "Sistema Surge",
    MANUAL_MECH_SURGE_DESC: "Empuja enemigos y MAGNETIZA toda la biomasa al instante.",
    MANUAL_MECH_COMBO_TITLE: "Cadena de Combo",
    MANUAL_MECH_COMBO_DESC: "Mata rápido para aumentar multiplicador. Recibir daño reinicia el combo.",
    STRAIN_STANDARD: "PATÓGENO ESTÁNDAR",
    STRAIN_SWARM: "ENJAMBRE MASIVO",
    STRAIN_TITAN: "TITÁN BLINDADO",
    STRAIN_VOLATILE: "MUTACIÓN VOLÁTIL",
    STRAIN_STD_DESC: "Parámetros de infección basais.",
    STRAIN_SWM_DESC: "Alto número de enemigos, menos vida individual.",
    STRAIN_TTN_DESC: "Enemigos con +100% Vida. Spawns más lentos.",
    STRAIN_VOL_DESC: "Enemigos mueven 30% más rápido. Alta agresión.",
    ROLE_DEV: "DESARROLLO",
    ROLE_DIR: "DIRECTOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Choque Séptico",
    SYMPTOM_VIRAL: "Carga Viral Desconocida",
    SYMPTOM_NECROTIC: "Tejido Necrótico",
    SYMPTOM_CYTOKINE: "Tormenta de Citocinas",
    SYMPTOM_FAILURE: "Fallo Orgánico",
    SYMPTOM_TOXICITY: "Toxicidad Sanguínea",
    SYMPTOM_DECAY: "Decadencia Celular",
    SYMPTOM_MUTATION: "Mutación Rápida",
    // HUD & In-Game Text
    LABEL_SYMPTOMS: "SÍNTOMAS",
    LABEL_ID: "ID",
    LABEL_AUDIO: "AUDIO",
    LABEL_OVERRIDE: "ANULACIÓN DEL SISTEMA",
    PH_ACCESS_CODE: "CÓDIGO DE ACCESO",
    MSG_SURGE: "¡SURGE!",
    MSG_ADRENALINE_EMPTY: "¡ADRENALINA AGOTADA!",
    MSG_BOSS_WARN: "ADVERTENCIA: JEFE",
    MSG_COMBO_LOST: "COMBO PERDIDO",
    MSG_RESTORED: "SISTEMA RESTAURADO",
    MSG_HP_PLUS: "+VIDA",
    MSG_BOOM: "¡BOOM!",
    MSG_COMBO_X: "¡COMBO!",
    NO_MUTATIONS: "NO SE DETECTARON MUTACIONES ACTIVAS",
    // Settings Keys
    AUDIO_PROTOCOLS: "PROTOCOLOS DE AUDIO",
    MASTER_OUTPUT: "VOLUMEN GENERAL",
    MUSIC_STREAM: "MÚSICA",
    SFX_FEEDBACK: "EFECTOS (SFX)",
    VISUAL_OPTICS: "ÓPTICA VISUAL",
    RETRO_FILTER: "FILTRO RETRO",
    CRT_DESC: "LÍNEAS CRT Y VIÑETA",
    SYSTEM_PURGE: "PURGAR SISTEMA (BORRAR)",
    CONFIRM_PURGE: "⚠️ ¿CONFIRMAR PURGA? ⚠️",
    HIGH_QUALITY: "FORZAR ALTA CALIDAD",
    HQ_WARNING: "AVISO: Desactivar el modo de rendimiento puede causar lag severo en este dispositivo.",
    // Upgrades
    UP_MITOSIS_NAME: "MITOSIS RÁPIDA",
    UP_MITOSIS_DESC: "+6% Cadencia de Tiro",
    UP_MEMBRANE_NAME: "MEMBRANA DE TITANIO",
    UP_MEMBRANE_DESC: "+12% Vida Máx & Cura Total",
    UP_ENZYME_NAME: "HIPER ENZIMAS",
    UP_ENZYME_DESC: "+8% Daño",
    UP_MULTISHOT_NAME: "DIVISIÓN ADAPTATIVA",
    UP_MULTISHOT_DESC: "+1 Proyectil, -25% Daño",
    UP_ENERGY_NAME: "IMPULSO MITOCONDRIAL",
    UP_ENERGY_DESC: "Surge y Esquiva recarga 8% más rápido",
    UP_GIGA_NAME: "TORMENTA CITOCINA",
    UP_GIGA_DESC: "+1 Proy, +20% Daño, Cura Total", // Nerfed
    UP_ORBITAL_NAME: "NANO-GUARDIANES",
    UP_ORBITAL_DESC: "Añade +1 Dron de Defensa Autónomo",
    UP_DASH_NAME: "RASTRO DE PLASMA",
    UP_DASH_DESC: "Dash causa 15 de Daño al atravesar enemigos",
    UP_CRIT_NAME: "ÓPTICA DE PRECISIÓN",
    UP_CRIT_DESC: "+4% Prob. Crítica, +0.15x Daño Crítico",
    UP_THORNS_NAME: "CAPARAZÓN DE ESPINAS",
    UP_THORNS_DESC: "Causa 1.5 de Daño al ser tocado",
    UP_LIFE_NAME: "CEPA VAMPÍRICA",
    UP_LIFE_DESC: "Bajas críticas curan +1 Vida",
    UP_MAGNET_NAME: "CAMPO MAGNÉTICO",
    UP_MAGNET_DESC: "+10% Rango de Imán y Tamaño de Surge",
    // Achievements
    ACH_KILL_100_TITLE: "Limpiador",
    ACH_KILL_100_DESC: "Elimina 100 patógenos.",
    ACH_KILL_1000_TITLE: "Esterilizador",
    ACH_KILL_1000_DESC: "Elimina 1.000 patógenos.",
    ACH_KILL_5000_TITLE: "Erradicador",
    ACH_KILL_5000_DESC: "Elimina 5.000 patógenos.",
    ACH_KILL_10000_TITLE: "Evento de Extinción",
    ACH_KILL_10000_DESC: "Elimina 10.000 patógenos.",
    ACH_BOSS_1_TITLE: "Anomalía Neutralizada",
    ACH_BOSS_1_DESC: "Derrota a tu primer Jefe.",
    ACH_BOSS_10_TITLE: "Asesino de Titanes",
    ACH_BOSS_10_DESC: "Derrota a 10 Jefes.",
    ACH_BOSS_50_TITLE: "Rey de las Venas",
    ACH_BOSS_50_DESC: "Derrota a 50 Jefes.",
    ACH_DASH_KILL_50_TITLE: "Atropello",
    ACH_DASH_KILL_50_DESC: "Mata 50 enemigos usando el daño de Dash.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Mata 100 enemigos con la explosión de Surge.",
    ACH_MINE_POP_20_TITLE: "Buscaminas",
    ACH_MINE_POP_20_DESC: "Detona 20 Bio-Minas.",
    ACH_BIOMASS_10K_TITLE: "Acaparador",
    ACH_BIOMASS_10K_DESC: "Recolecta un total de 10.000 de Biomasa.",
    ACH_WAVE_5_TITLE: "Sobrevivente",
    ACH_WAVE_5_DESC: "Llega a la Oleada 5.",
    ACH_WAVE_10_TITLE: "Inmersión Profunda",
    ACH_WAVE_10_DESC: "Llega a la Oleada 10 (Modo Infinito).",
    ACH_SCORE_50K_TITLE: "Puntuación Máxima",
    ACH_SCORE_50K_DESC: "Alcanza 50.000 puntos en una partida.",
    ACH_COMBO_50_TITLE: "Estado de Flujo",
    ACH_COMBO_50_DESC: "Alcanza un Combo de 50x.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Alcanza 200 de Vida Máxima en una partida.",
    ACH_FIRE_RATE_MAX_TITLE: "Ametralladora",
    ACH_FIRE_RATE_MAX_DESC: "Maximiza la mejora de Cadencia de Tiro.",
    ACH_PERFECT_WAVE_TITLE: "Intocable",
    ACH_PERFECT_WAVE_DESC: "Completa una oleada sin recibir daño.",
    ACH_LOW_HP_SURVIVE_TITLE: "Adicto a la Adrenalina",
    ACH_LOW_HP_SURVIVE_DESC: "Gana una oleada con < 20% de Vida.",
    ACH_CRIT_MASTER_TITLE: "Precisión Quirúrgica",
    ACH_CRIT_MASTER_DESC: "Acierta 1.000 Críticos.",
    ACH_UNLOCK_ALL_TITLE: "Perfección Genética",
    ACH_UNLOCK_ALL_DESC: "Compra todos los tipos de mejora al menos una vez.",
    ACH_WIN_APEX_TITLE: "Depredador Apex",
    ACH_WIN_APEX_DESC: "Completa la Oleada 5 en dificultad APEX.",
    ACH_DIE_10_TITLE: "Prueba y Error",
    ACH_DIE_10_DESC: "Muere 10 veces.",
    ACH_AFK_TITLE: "Estatua",
    ACH_AFK_DESC: "Quédate quieto durante 10 segundos en combate.",
    ACH_PACIFIST_TITLE: "Pacifista",
    ACH_PACIFIST_DESC: "Sobrevive 30 segundos sin disparar.",
    ACH_OVERKILL_TITLE: "Exagerado",
    ACH_OVERKILL_DESC: "Inflige más de 500 de daño en un solo golpe.",
    ACH_RICH_TITLE: "Magnate",
    ACH_RICH_DESC: "Ten 3.000 de Biomasa al mismo tiempo.",
    ACH_PLAY_TIME_1H_TITLE: "Becario",
    ACH_PLAY_TIME_1H_DESC: "Juega durante 1 hora (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Especialista",
    ACH_PLAY_TIME_5H_DESC: "Juega durante 5 horas (Total).",
    ACH_ALL_TITLE: "EL VIRUS APEX",
    ACH_ALL_DESC: "Desbloquea todos los demás logros."
  }
};

// Configuração das Ondas.
// Ajustado para o modo "Pesadelo". Spawns mais rápidos desde o começo.
export const WAVES: WaveConfig[] = [
    // WAVE 1: Intro (Bacteria) - 30s
    { waveNumber: 1, duration: 30, spawnRate: 600, enemyTypes: [EntityType.BACTERIA], flowSpeed: -0.4, hasBoss: false },
    // WAVE 2: Intro (Fungi) - 35s
    { waveNumber: 2, duration: 35, spawnRate: 550, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI], flowSpeed: -0.5, hasBoss: false },
    // WAVE 3: Mix - 40s
    { waveNumber: 3, duration: 40, spawnRate: 500, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI], flowSpeed: -0.6, hasBoss: false },
    // WAVE 4: Intro (Virus - Shooter) - 45s
    { waveNumber: 4, duration: 45, spawnRate: 500, enemyTypes: [EntityType.BACTERIA, EntityType.VIRUS], flowSpeed: -0.7, hasBoss: false },
    // WAVE 5: First Boss (Mini-check) - 50s
    { waveNumber: 5, duration: 50, spawnRate: 450, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.VIRUS], flowSpeed: -0.8, hasBoss: true },
    // WAVE 6: Intro (Parasite - Tank) - 50s
    { waveNumber: 6, duration: 50, spawnRate: 450, enemyTypes: [EntityType.FUNGI, EntityType.PARASITE], flowSpeed: -0.9, hasBoss: false },
    // WAVE 7: Swarm Chaos (Fungi + Bacteria) - 55s
    { waveNumber: 7, duration: 55, spawnRate: 350, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI], flowSpeed: -1.0, hasBoss: false },
    // WAVE 8: Heavy Hitters (Virus + Parasite) - 60s
    { waveNumber: 8, duration: 60, spawnRate: 400, enemyTypes: [EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.1, hasBoss: false },
    // WAVE 9: Pre-Boss Intensity - 60s
    { waveNumber: 9, duration: 60, spawnRate: 350, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.2, hasBoss: false },
    // WAVE 10: Major Boss - 60s
    { waveNumber: 10, duration: 60, spawnRate: 300, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.VIRUS], flowSpeed: -1.3, hasBoss: true },
    // WAVE 11-14: Escalation
    { waveNumber: 11, duration: 65, spawnRate: 300, enemyTypes: [EntityType.BACTERIA, EntityType.PARASITE], flowSpeed: -1.4, hasBoss: false },
    { waveNumber: 12, duration: 65, spawnRate: 280, enemyTypes: [EntityType.FUNGI, EntityType.VIRUS], flowSpeed: -1.5, hasBoss: false },
    { waveNumber: 13, duration: 70, spawnRate: 260, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.PARASITE], flowSpeed: -1.6, hasBoss: false },
    { waveNumber: 14, duration: 70, spawnRate: 250, enemyTypes: [EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.7, hasBoss: false },
    // WAVE 15: Boss
    { waveNumber: 15, duration: 75, spawnRate: 240, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.8, hasBoss: true },
    // WAVE 16-19: High Speed
    { waveNumber: 16, duration: 75, spawnRate: 220, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI], flowSpeed: -2.0, hasBoss: false },
    { waveNumber: 17, duration: 80, spawnRate: 200, enemyTypes: [EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -2.2, hasBoss: false },
    { waveNumber: 18, duration: 80, spawnRate: 190, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.VIRUS], flowSpeed: -2.4, hasBoss: false },
    { waveNumber: 19, duration: 85, spawnRate: 180, enemyTypes: [EntityType.FUNGI, EntityType.PARASITE], flowSpeed: -2.6, hasBoss: false },
    // WAVE 20: ENDLESS (The Wall)
    { waveNumber: 20, duration: 9999, spawnRate: 150, enemyTypes: [EntityType.BACTERIA, EntityType.FUNGI, EntityType.PARASITE, EntityType.VIRUS], flowSpeed: -3.0, hasBoss: true },
];

// O "Shopping" do jogo.
// Inflação aplicada. Tudo custa o olho da cara.
export const UPGRADES: Upgrade[] = [
  {
    id: 'mitosis',
    nameKey: 'UP_MITOSIS_NAME',
    descKey: 'UP_MITOSIS_DESC',
    rarity: 'COMMON',
    baseCost: 200,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, fireRate: Math.max(150, s.fireRate * 0.94) }) // Nerfado (era 0.92)
  },
  {
    id: 'enzyme',
    nameKey: 'UP_ENZYME_NAME',
    descKey: 'UP_ENZYME_DESC',
    rarity: 'RARE',
    baseCost: 350,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, damage: s.damage * 1.08 }) // Nerfado (era 1.10)
  },
  {
    id: 'membrane',
    nameKey: 'UP_MEMBRANE_NAME',
    descKey: 'UP_MEMBRANE_DESC',
    rarity: 'COMMON',
    baseCost: 250,
    costMultiplier: 1.6,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, maxHealth: Math.floor(s.maxHealth * 1.12), health: Math.floor(s.maxHealth * 1.12) }) // Nerfado (era 1.15)
  },
  {
    id: 'multishot',
    nameKey: 'UP_MULTISHOT_NAME',
    descKey: 'UP_MULTISHOT_DESC',
    rarity: 'EPIC',
    baseCost: 1000,
    costMultiplier: 2.5,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, bulletCount: s.bulletCount + 1, damage: s.damage * 0.75 }) // Nerfado (penalidade maior -25%)
  },
  {
    id: 'orbitals',
    nameKey: 'UP_ORBITAL_NAME',
    descKey: 'UP_ORBITAL_DESC',
    rarity: 'EPIC',
    baseCost: 1500, // Ficou caro demais pra comprar no começo
    costMultiplier: 3.0,
    level: 0,
    maxLevel: 4,
    apply: (s) => ({ ...s, orbitals: s.orbitals + 1 })
  },
  {
    id: 'crit',
    nameKey: 'UP_CRIT_NAME',
    descKey: 'UP_CRIT_DESC',
    rarity: 'RARE',
    baseCost: 500,
    costMultiplier: 2.0,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, critChance: s.critChance + 0.04, critMultiplier: s.critMultiplier + 0.15 }) // Nerfado
  },
  {
    id: 'dash_dmg',
    nameKey: 'UP_DASH_NAME',
    descKey: 'UP_DASH_DESC',
    rarity: 'COMMON',
    baseCost: 300,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, dashDamage: s.dashDamage + 15 }) // Nerfado (era 20)
  },
  {
    id: 'thorns',
    nameKey: 'UP_THORNS_NAME',
    descKey: 'UP_THORNS_DESC',
    rarity: 'COMMON',
    baseCost: 400,
    costMultiplier: 2.0,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, thorns: s.thorns + 1.5 }) // Nerfado (2 -> 1.5)
  },
  {
    id: 'lifesteal',
    nameKey: 'UP_LIFE_NAME',
    descKey: 'UP_LIFE_DESC',
    rarity: 'LEGENDARY',
    baseCost: 3000, // Preço AUMENTADO (era 2000)
    costMultiplier: 4.0, // Inflação AUMENTADA (era 3.5)
    level: 0,
    maxLevel: 3,
    apply: (s) => ({ ...s, lifesteal: s.lifesteal + 0.05 })
  },
  {
    id: 'magnet',
    nameKey: 'UP_MAGNET_NAME',
    descKey: 'UP_MAGNET_DESC',
    rarity: 'COMMON',
    baseCost: 200,
    costMultiplier: 1.5,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, magnetRadius: s.magnetRadius * 1.10, surgeRadiusMult: s.surgeRadiusMult * 1.1 }) // Nerfado
  },
  {
    id: 'energy_core',
    nameKey: 'UP_ENERGY_NAME',
    descKey: 'UP_ENERGY_DESC',
    rarity: 'RARE',
    baseCost: 400,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, maxEnergy: Math.max(50, s.maxEnergy * 0.92), dashCooldown: Math.max(400, s.dashCooldown * 0.92) }) // Nerfado (8%)
  },
  {
    id: 'giga_blast',
    nameKey: 'UP_GIGA_NAME',
    descKey: 'UP_GIGA_DESC',
    rarity: 'LEGENDARY',
    baseCost: 3000, // Aumentado (era 2500)
    costMultiplier: 3.5, // Aumentado (era 3.0)
    level: 0,
    maxLevel: 3,
    apply: (s) => ({ ...s, bulletCount: s.bulletCount + 1, damage: s.damage * 1.20, health: s.maxHealth }) // NERFADO: +1 Proj (era +2), Buff de dano pra compensar
  }
];
