/**
 * ------------------------------------------------------------------
 * COPYRIGHT (c) 2026 ESTÚDIO CRIA
 * DIRETOR: PAULO GABRIEL DE L. S.
 * ------------------------------------------------------------------
 * 
 * BEM-VINDO AO DNA DO JOGO - VERSÃO "PREPARE TO DIE"
 * 
 * O usuário reclamou que estava fácil. O usuário pediu dor.
 * O usuário receberá dor.
 * 
 * Ajustamos a economia para simular uma crise financeira global.
 * Os inimigos agora tomam suplementos ilegais.
 * O jogador foi nerfado para a idade da pedra.
 */

import { Upgrade, EntityType, WaveConfig, Language, Difficulty, Achievement, ThemePalette } from './types';

// --- PALETA DE CORES ---
export const COLORS_DEFAULT: ThemePalette = {
  BG: '#1a0505',
  PLAYER: '#ffffff',
  PLAYER_CORE: '#00ffff',
  BACTERIA: '#77dd77',
  VIRUS: '#ff00ff',
  PARASITE: '#ff3333',
  BOSS: '#880000', 
  ELITE_GLOW: '#ffd700',
  ANTIBODY: '#00ffff',
  DNA: '#ffeeaa',
  BLOOD_PARTICLE: '#3a0a0a',
  UI_ACCENT: '#ff4444',
  SURGE: 'rgba(0, 255, 255, 0.3)',
  COMBO: '#ffaa00',
  ORBITAL: '#0088ff',
  BIO_MINE: '#00ff44',
  ACID_POOL: '#33ff00'
};

export const COLORS_PLATINUM: ThemePalette = {
  BG: '#0a0a1a', 
  PLAYER: '#ffffff',
  PLAYER_CORE: '#ffd700',
  BACTERIA: '#b39ddb', 
  VIRUS: '#80deea', 
  PARASITE: '#f48fb1', 
  BOSS: '#ffd700', 
  ELITE_GLOW: '#ffffff', 
  ANTIBODY: '#ffd700',
  DNA: '#e1bee7', 
  BLOOD_PARTICLE: '#1a1a2e', 
  UI_ACCENT: '#ffd700', 
  SURGE: 'rgba(255, 215, 0, 0.3)', 
  COMBO: '#ffffff',
  ORBITAL: '#ffd700',
  BIO_MINE: '#ff4081',
  ACID_POOL: '#7c4dff'
};

export const CANVAS_WIDTH = 1920;
export const CANVAS_HEIGHT = 1080;

// Configurações de Sobrevivência
export const INITIAL_LIVES = 3; // Três chances. Não desperdice.
export const ADRENALINE_MAX_DURATION = 20; // Segundos. Depois disso, o coração explode se não parar.

// Status iniciais do "Heroi". 
// NERF: Reduzimos tudo. Você não é mais um Rambo, é um estagiário com uma pistola de água.
export const INITIAL_STATS = {
  speed: 4.0, // Um pouco mais lento pra dar agonia
  fireRate: 450, // Muito mais lento. Clique ou morra.
  damage: 15, // Dano de mosquito
  bulletSpeed: 16, 
  bulletCount: 1,
  magnetRadius: 100, // Vai ter que andar pra pegar dinheiro
  maxHealth: 80, // Papel
  regen: 0, // Regeneração? Isso é coisa de jogo fácil. Começa com ZERO.
  maxEnergy: 120, // Mais difícil de ultar
  dashSpeed: 22, 
  dashCooldown: 1500, // Cooldown maior
  critChance: 0.01, // 1% de chance. Boa sorte.
  critMultiplier: 1.2,
  orbitals: 0,
  thorns: 0,
  lifesteal: 0,
  dashDamage: 0,
  surgeRadiusMult: 0.8
};

// Multiplicadores de dificuldade.
// AGORA A BRINCADEIRA FICOU SÉRIA.
export const DIFFICULTY_MODIFIERS = {
  [Difficulty.EASY]: { hp: 1.0, dmg: 1.0, speed: 1.0, score: 0.8 }, // O Easy virou o antigo Normal
  [Difficulty.NORMAL]: { hp: 1.8, dmg: 1.5, speed: 1.2, score: 1.0 }, // Normal já dói
  [Difficulty.HARD]: { hp: 3.0, dmg: 2.5, speed: 1.4, score: 1.5 }, // Hard é para masoquistas
  [Difficulty.APEX]: { hp: 5.5, dmg: 4.0, speed: 1.7, score: 3.0 } // APEX: Inimigos são tanques de guerra com propulsores
};

export const PATIENT_NAMES_FIRST = ["J.", "A.", "M.", "K.", "R.", "S.", "T.", "L.", "C.", "B."];
export const PATIENT_NAMES_LAST = ["Doe", "Smith", "Neo", "Kovac", "Vane", "Ross", "Cole", "Drake", "Pike", "Ward"];

export const SYMPTOMS_KEYS = [
  "SYMPTOM_SEPTIC", "SYMPTOM_VIRAL", "SYMPTOM_NECROTIC", "SYMPTOM_CYTOKINE", 
  "SYMPTOM_FAILURE", "SYMPTOM_TOXICITY", "SYMPTOM_DECAY", "SYMPTOM_MUTATION"
];

export const ACHIEVEMENTS_LIST: Achievement[] = [
    { id: 'kill_100', icon: '🦠', titleKey: 'ACH_KILL_100_TITLE', descKey: 'ACH_KILL_100_DESC', targetValue: 100, isCumulative: true },
    { id: 'kill_1000', icon: '🧹', titleKey: 'ACH_KILL_1000_TITLE', descKey: 'ACH_KILL_1000_DESC', targetValue: 1000, isCumulative: true },
    { id: 'kill_5000', icon: '🔥', titleKey: 'ACH_KILL_5000_TITLE', descKey: 'ACH_KILL_5000_DESC', targetValue: 5000, isCumulative: true },
    { id: 'kill_10000', icon: '💀', titleKey: 'ACH_KILL_10000_TITLE', descKey: 'ACH_KILL_10000_DESC', targetValue: 10000, isCumulative: true },
    { id: 'boss_1', icon: '👾', titleKey: 'ACH_BOSS_1_TITLE', descKey: 'ACH_BOSS_1_DESC', targetValue: 1, isCumulative: true },
    { id: 'boss_10', icon: '👹', titleKey: 'ACH_BOSS_10_TITLE', descKey: 'ACH_BOSS_10_DESC', targetValue: 10, isCumulative: true },
    { id: 'boss_50', icon: '👑', titleKey: 'ACH_BOSS_50_TITLE', descKey: 'ACH_BOSS_50_DESC', targetValue: 50, isCumulative: true },
    { id: 'dash_kill_50', icon: '⚡', titleKey: 'ACH_DASH_KILL_50_TITLE', descKey: 'ACH_DASH_KILL_50_DESC', targetValue: 50, isCumulative: true },
    { id: 'surge_kill_100', icon: '🌊', titleKey: 'ACH_SURGE_KILL_100_TITLE', descKey: 'ACH_SURGE_KILL_100_DESC', targetValue: 100, isCumulative: true },
    { id: 'mine_pop_20', icon: '💣', titleKey: 'ACH_MINE_POP_20_TITLE', descKey: 'ACH_MINE_POP_20_DESC', targetValue: 20, isCumulative: true },
    { id: 'biomass_10k', icon: '💎', titleKey: 'ACH_BIOMASS_10K_TITLE', descKey: 'ACH_BIOMASS_10K_DESC', targetValue: 10000, isCumulative: true },
    { id: 'wave_5', icon: '🖐', titleKey: 'ACH_WAVE_5_TITLE', descKey: 'ACH_WAVE_5_DESC', targetValue: 5, isCumulative: false },
    { id: 'wave_10', icon: '🧗', titleKey: 'ACH_WAVE_10_TITLE', descKey: 'ACH_WAVE_10_DESC', targetValue: 10, isCumulative: false },
    { id: 'score_50k', icon: '📈', titleKey: 'ACH_SCORE_50K_TITLE', descKey: 'ACH_SCORE_50K_DESC', targetValue: 50000, isCumulative: false },
    { id: 'combo_50', icon: '⛓', titleKey: 'ACH_COMBO_50_TITLE', descKey: 'ACH_COMBO_50_DESC', targetValue: 50, isCumulative: false },
    { id: 'max_hp_200', icon: '❤️', titleKey: 'ACH_MAX_HP_200_TITLE', descKey: 'ACH_MAX_HP_200_DESC', targetValue: 200, isCumulative: false },
    { id: 'fire_rate_max', icon: '🔫', titleKey: 'ACH_FIRE_RATE_MAX_TITLE', descKey: 'ACH_FIRE_RATE_MAX_DESC', targetValue: 1, isCumulative: false },
    { id: 'perfect_wave', icon: '✨', titleKey: 'ACH_PERFECT_WAVE_TITLE', descKey: 'ACH_PERFECT_WAVE_DESC', targetValue: 1, isCumulative: true },
    { id: 'low_hp_survive', icon: '🚑', titleKey: 'ACH_LOW_HP_SURVIVE_TITLE', descKey: 'ACH_LOW_HP_SURVIVE_DESC', targetValue: 1, isCumulative: true },
    { id: 'crit_master', icon: '🎯', titleKey: 'ACH_CRIT_MASTER_TITLE', descKey: 'ACH_CRIT_MASTER_DESC', targetValue: 1000, isCumulative: true },
    { id: 'unlock_all_upgrades', icon: '🧬', titleKey: 'ACH_UNLOCK_ALL_TITLE', descKey: 'ACH_UNLOCK_ALL_DESC', targetValue: 12, isCumulative: true },
    { id: 'win_apex', icon: '🏆', titleKey: 'ACH_WIN_APEX_TITLE', descKey: 'ACH_WIN_APEX_DESC', targetValue: 1, isCumulative: false },
    { id: 'die_10', icon: '⚰️', titleKey: 'ACH_DIE_10_TITLE', descKey: 'ACH_DIE_10_DESC', targetValue: 10, isCumulative: true },
    { id: 'afk', icon: '🗿', titleKey: 'ACH_AFK_TITLE', descKey: 'ACH_AFK_DESC', targetValue: 10, isCumulative: false, secret: true },
    { id: 'pacifist', icon: '🕊', titleKey: 'ACH_PACIFIST_TITLE', descKey: 'ACH_PACIFIST_DESC', targetValue: 30, isCumulative: false, secret: true },
    { id: 'overkill', icon: '💥', titleKey: 'ACH_OVERKILL_TITLE', descKey: 'ACH_OVERKILL_DESC', targetValue: 1, isCumulative: true },
    { id: 'rich', icon: '💰', titleKey: 'ACH_RICH_TITLE', descKey: 'ACH_RICH_DESC', targetValue: 3000, isCumulative: false },
    { id: 'play_time_1h', icon: '⏳', titleKey: 'ACH_PLAY_TIME_1H_TITLE', descKey: 'ACH_PLAY_TIME_1H_DESC', targetValue: 3600, isCumulative: true },
    { id: 'play_time_5h', icon: '👨‍⚕️', titleKey: 'ACH_PLAY_TIME_5H_TITLE', descKey: 'ACH_PLAY_TIME_5H_DESC', targetValue: 18000, isCumulative: true },
    { id: 'all_achievements', icon: '💠', titleKey: 'ACH_ALL_TITLE', descKey: 'ACH_ALL_DESC', targetValue: 1, isCumulative: true, secret: true }
];

type TranslationMap = {
  [key in Language]: {
    [key: string]: string;
  };
};

export const TEXTS: TranslationMap = {
  EN: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INJECT",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLS",
    MANUAL: "DATABASE",
    CREDITS: "CREDITS",
    LANG: "LANGUAGE",
    BACK: "RETURN",
    PAUSED: "SYSTEM PAUSED",
    RESUME: "RESUME",
    ABORT: "ABORT MISSION",
    GAME_OVER: "PATIENT LOST",
    RETRY: "NEXT PATIENT",
    WAVE: "WAVE",
    SCORE: "SCORE",
    CLEARED: "STABILIZED",
    NEXT: "NEXT SECTOR",
    MUTATION: "BIO-LAB",
    SELECT_DNA: "SPEND BIOMASS TO EVOLVE",
    SURGE_READY: "SURGE",
    DEPLOY: "DEPLOY",
    BRIEFING: "PATIENT CHART",
    BOSS_WARNING: "ANOMALY DETECTED",
    OPEN_SHOP: "OPEN BIO-LAB",
    PURCHASE: "EVOLVE",
    COST: "COST",
    MAXED: "MAX",
    COMBO: "COMBO",
    DASH: "DASH",
    DIFFICULTY: "RISK LEVEL",
    PATIENT: "SUBJECT",
    STRAIN: "STRAIN",
    BIOMASS_AVAIL: "BIOMASS AVAILABLE",
    AUDIO_LINK: "AUDIO LINK",
    STATUS_TERM: "STATUS: TERMINATED",
    INTEGRITY: "INTEGRITY",
    ADRENALINE: "ADRENALINA ACTIVE",
    LOADOUT: "ACTIVE GENOME",
    ACHIEVEMENTS: "ACHIEVEMENTS",
    ACH_LOCKED: "LOCKED",
    ACH_PROGRESS: "PROGRESS",
    ACH_PLATINUM_MSG: "SYSTEM OVERRIDE: APEX MODE ENGAGED. VISUALS EVOLVED.",
    DIFF_TRIAGE: "TRIAGE",
    DIFF_RESIDENT: "RESIDENT",
    DIFF_SPECIALIST: "SPECIALIST",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVEMENT",
    CTRL_MOVE_DESC: "WASD / ARROWS / TOUCH JOYSTICK",
    CTRL_DASH: "DASH / EVADE",
    CTRL_DASH_DESC: "SHIFT / E / TOUCH BUTTON",
    CTRL_SURGE: "SURGE ULTIMATE",
    CTRL_SURGE_DESC: "SPACE / TOUCH BUTTON",
    CTRL_NOTE: "AUTO-FIRE IS ALWAYS ENGAGED",
    MANUAL_HOSTILES: "HOSTILES",
    MANUAL_STRAINS: "VIRAL STRAINS",
    MANUAL_MECHANICS: "BATTLE MECHANICS",
    MANUAL_BAC_DESC: "Standard pathogen. Common, predictable movement.",
    MANUAL_VIR_DESC: "Fast attacker. Low HP but swarms quickly.",
    MANUAL_PAR_DESC: "Heavy tank. Slow, high HP, absorbs damage.",
    MANUAL_BOSS_DESC: "Massive anomaly. Requires extreme firepower.",
    MANUAL_MECH_DASH_TITLE: "Evasive Dash",
    MANUAL_MECH_DASH_DESC: "Grants momentary invulnerability. Use to pass through enemies.",
    MANUAL_MECH_SURGE_TITLE: "Surge System",
    MANUAL_MECH_SURGE_DESC: "Push enemies back and MAGNETIZE all biomass instantly.",
    MANUAL_MECH_COMBO_TITLE: "Combo Chain",
    MANUAL_MECH_COMBO_DESC: "Kill fast to increase score multiplier. Taking damage resets combo.",
    STRAIN_STANDARD: "STANDARD PATHOGEN",
    STRAIN_SWARM: "SWARM CLUSTER",
    STRAIN_TITAN: "ARMORED TITAN",
    STRAIN_VOLATILE: "VOLATILE MUTATION",
    STRAIN_STD_DESC: "Baseline infection parameters.",
    STRAIN_SWM_DESC: "High enemy count, lower individual HP.",
    STRAIN_TTN_DESC: "Enemies have +100% HP. Slower spawns.",
    STRAIN_VOL_DESC: "Enemies move 30% faster. High aggression.",
    ROLE_DEV: "DEVELOPMENT",
    ROLE_DIR: "DIRECTOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Septic Shock",
    SYMPTOM_VIRAL: "Unknown Viral Load",
    SYMPTOM_NECROTIC: "Necrotic Tissue",
    SYMPTOM_CYTOKINE: "Cytokine Storm",
    SYMPTOM_FAILURE: "Organ Failure",
    SYMPTOM_TOXICITY: "Blood Toxicity",
    SYMPTOM_DECAY: "Cellular Decay",
    SYMPTOM_MUTATION: "Rapid Mutation",
    // Upgrades
    UP_MITOSIS_NAME: "RAPID MITOSIS",
    UP_MITOSIS_DESC: "+10% Fire Rate",
    UP_MEMBRANE_NAME: "TITANIUM MEMBRANE",
    UP_MEMBRANE_DESC: "+25% Max HP & Full Heal",
    UP_ENZYME_NAME: "HYPER ENZYMES",
    UP_ENZYME_DESC: "+15% Damage",
    UP_MULTISHOT_NAME: "ADAPTIVE SPLIT",
    UP_MULTISHOT_DESC: "+1 Projectile, -15% Damage",
    UP_ENERGY_NAME: "MITOCHONDRIA BOOST",
    UP_ENERGY_DESC: "Surge & Dash recharge 15% faster",
    UP_GIGA_NAME: "CYTOKINE STORM",
    UP_GIGA_DESC: "+2 Proj, +20% Dmg, Full Heal",
    UP_ORBITAL_NAME: "NANO-GUARDIANS",
    UP_ORBITAL_DESC: "Adds +1 Autonomous Defensive Drone",
    UP_DASH_NAME: "PLASMA TRAIL",
    UP_DASH_DESC: "Dash deals 30 Damage to enemies passed",
    UP_CRIT_NAME: "PRECISION OPTICS",
    UP_CRIT_DESC: "+10% Crit Chance, +0.3x Crit Dmg",
    UP_THORNS_NAME: "SPIKED CARAPACE",
    UP_THORNS_DESC: "Deals 3 Contact Dmg to attackers",
    UP_LIFE_NAME: "VAMPIRIC STRAIN",
    UP_LIFE_DESC: "Crit kills heal +1 HP",
    UP_MAGNET_NAME: "MAGNETIC FIELD",
    UP_MAGNET_DESC: "+20% Magnet Range & Surge Radius",
    // Achievements
    ACH_KILL_100_TITLE: "Cleaner",
    ACH_KILL_100_DESC: "Eliminate 100 pathogens.",
    ACH_KILL_1000_TITLE: "Sterilizer",
    ACH_KILL_1000_DESC: "Eliminate 1,000 pathogens.",
    ACH_KILL_5000_TITLE: "Eradicator",
    ACH_KILL_5000_DESC: "Eliminate 5,000 pathogens.",
    ACH_KILL_10000_TITLE: "Extinction Event",
    ACH_KILL_10000_DESC: "Eliminate 10,000 pathogens.",
    ACH_BOSS_1_TITLE: "Anomaly Neutralized",
    ACH_BOSS_1_DESC: "Defeat your first Boss.",
    ACH_BOSS_10_TITLE: "Titan Slayer",
    ACH_BOSS_10_DESC: "Defeat 10 Bosses.",
    ACH_BOSS_50_TITLE: "King of Veins",
    ACH_BOSS_50_DESC: "Defeat 50 Bosses.",
    ACH_DASH_KILL_50_TITLE: "Roadkill",
    ACH_DASH_KILL_50_DESC: "Kill 50 enemies using Dash damage.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Kill 100 enemies with Surge blasts.",
    ACH_MINE_POP_20_TITLE: "Minesweeper",
    ACH_MINE_POP_20_DESC: "Detonate 20 Bio-Mines.",
    ACH_BIOMASS_10K_TITLE: "Hoarder",
    ACH_BIOMASS_10K_DESC: "Collect 10,000 total Biomass.",
    ACH_WAVE_5_TITLE: "Survivor",
    ACH_WAVE_5_DESC: "Reach Wave 5.",
    ACH_WAVE_10_TITLE: "Deep Dive",
    ACH_WAVE_10_DESC: "Reach Wave 10 (Endless Mode).",
    ACH_SCORE_50K_TITLE: "High Score",
    ACH_SCORE_50K_DESC: "Reach 50,000 Score in one run.",
    ACH_COMBO_50_TITLE: "Flow State",
    ACH_COMBO_50_DESC: "Reach a 50x Combo.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Reach 200 Max HP in a run.",
    ACH_FIRE_RATE_MAX_TITLE: "Minigun",
    ACH_FIRE_RATE_MAX_DESC: "Max out Fire Rate upgrade.",
    ACH_PERFECT_WAVE_TITLE: "Untouchable",
    ACH_PERFECT_WAVE_DESC: "Complete a wave without taking damage.",
    ACH_LOW_HP_SURVIVE_TITLE: "Adrenaline Junkie",
    ACH_LOW_HP_SURVIVE_DESC: "Clear a wave with < 20% HP.",
    ACH_CRIT_MASTER_TITLE: "Surgical Precision",
    ACH_CRIT_MASTER_DESC: "Land 1,000 Critical Hits.",
    ACH_UNLOCK_ALL_TITLE: "Genetic Perfection",
    ACH_UNLOCK_ALL_DESC: "Buy every type of upgrade at least once (Cumulative).",
    ACH_WIN_APEX_TITLE: "Apex Predator",
    ACH_WIN_APEX_DESC: "Clear Wave 5 on APEX difficulty.",
    ACH_DIE_10_TITLE: "Trial and Error",
    ACH_DIE_10_DESC: "Die 10 times.",
    ACH_AFK_TITLE: "Statue",
    ACH_AFK_DESC: "Stand still for 10 seconds in combat.",
    ACH_PACIFIST_TITLE: "Pacifist",
    ACH_PACIFIST_DESC: "Survive 30 seconds without shooting.",
    ACH_OVERKILL_TITLE: "Overkill",
    ACH_OVERKILL_DESC: "Deal over 500 damage in a single hit.",
    ACH_RICH_TITLE: "Tycoon",
    ACH_RICH_DESC: "Hold 3,000 Biomass at once.",
    ACH_PLAY_TIME_1H_TITLE: "Intern",
    ACH_PLAY_TIME_1H_DESC: "Play for 1 hour (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Specialist",
    ACH_PLAY_TIME_5H_DESC: "Play for 5 hours (Total).",
    ACH_ALL_TITLE: "THE APEX VIRUS",
    ACH_ALL_DESC: "Unlock all other achievements."
  },
  PT: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INJETAR",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLES",
    MANUAL: "BANCO DE DADOS",
    CREDITS: "CRÉDITOS",
    LANG: "IDIOMA",
    BACK: "VOLTAR",
    PAUSED: "SISTEMA PAUSADO",
    RESUME: "RETOMAR",
    ABORT: "ABORTAR MISSÃO",
    GAME_OVER: "PACIENTE PERDIDO",
    RETRY: "PRÓXIMO PACIENTE",
    WAVE: "ONDA",
    SCORE: "PONTOS",
    CLEARED: "ESTABILIZADO",
    NEXT: "PRÓXIMO SETOR",
    MUTATION: "BIO-LABORATÓRIO",
    SELECT_DNA: "GASTAR BIOMASSA PARA EVOLUIR",
    SURGE_READY: "SURTO",
    DEPLOY: "IMPLANTAR",
    BRIEFING: "PRONTUÁRIO",
    BOSS_WARNING: "ANOMALIA DETECTADA",
    OPEN_SHOP: "ABRIR BIO-LAB",
    PURCHASE: "EVOLUIR",
    COST: "CUSTO",
    MAXED: "MÁX",
    COMBO: "COMBO",
    DASH: "ESQUIVA",
    DIFFICULTY: "NÍVEL DE RISCO",
    PATIENT: "SUJEITO",
    STRAIN: "CEPA",
    BIOMASS_AVAIL: "BIOMASSA DISPONÍVEL",
    AUDIO_LINK: "LINK DE ÁUDIO",
    STATUS_TERM: "STATUS: TERMINADO",
    INTEGRITY: "INTEGRIDADE",
    ADRENALINE: "ADRENALINA ATIVA",
    LOADOUT: "GENOMA ATIVO",
    ACHIEVEMENTS: "CONQUISTAS",
    ACH_LOCKED: "BLOQUEADO",
    ACH_PROGRESS: "PROGRESSO",
    ACH_PLATINUM_MSG: "SOBREPOSIÇÃO DE SISTEMA: MODO APEX ATIVADO. VISUALES EVOLUÍDOS.",
    DIFF_TRIAGE: "TRIAGEM",
    DIFF_RESIDENT: "RESIDENTE",
    DIFF_SPECIALIST: "ESPECIALISTA",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVIMENTO",
    CTRL_MOVE_DESC: "WASD / SETAS / JOYSTICK NA TELA",
    CTRL_DASH: "ESQUIVA RÁPIDA",
    CTRL_DASH_DESC: "SHIFT / E / BOTÃO NA TELA",
    CTRL_SURGE: "SURTO SUPREMO",
    CTRL_SURGE_DESC: "ESPAÇO / BOTÃO NA TELA",
    CTRL_NOTE: "DISPARO AUTOMÁTICO SEMPRE ATIVO",
    MANUAL_HOSTILES: "HOSTIS",
    MANUAL_STRAINS: "CEPAS VIRAIS",
    MANUAL_MECHANICS: "MECÂNICAS DE COMBATE",
    MANUAL_BAC_DESC: "Patógeno padrão. Movimento comum e previsível.",
    MANUAL_VIR_DESC: "Atacante rápido. Pouca vida, mas ataca em enxame.",
    MANUAL_PAR_DESC: "Tanque pesado. Lento, muita vida, absorve dano.",
    MANUAL_BOSS_DESC: "Anomalia massiva. Requer poder de fogo extremo.",
    MANUAL_MECH_DASH_TITLE: "Esquiva (Dash)",
    MANUAL_MECH_DASH_DESC: "Concede invulnerabilidade momentânea. Use para atravessar inimigos.",
    MANUAL_MECH_SURGE_TITLE: "Sistema de Surto",
    MANUAL_MECH_SURGE_DESC: "Empurra inimigos e MAGNETIZA toda biomassa instantaneamente.",
    MANUAL_MECH_COMBO_TITLE: "Corrente de Combo",
    MANUAL_MECH_COMBO_DESC: "Mate rápido para aumentar multiplicador. Levar dano zera o combo.",
    STRAIN_STANDARD: "PATÓGENO PADRÃO",
    STRAIN_SWARM: "ENXAME MASSIVO",
    STRAIN_TITAN: "TITÃ BLINDADO",
    STRAIN_VOLATILE: "MUTAÇÃO VOLÁTIL",
    STRAIN_STD_DESC: "Parâmetros de infecção basais.",
    STRAIN_SWM_DESC: "Alto número de inimigos, menos vida individual.",
    STRAIN_TTN_DESC: "Inimigos com +100% Vida. Spawns mais lentos.",
    STRAIN_VOL_DESC: "Inimigos movem 30% mais rápido. Alta agressão.",
    ROLE_DEV: "DESENVOLVIMENTO",
    ROLE_DIR: "DIRETOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Choque Séptico",
    SYMPTOM_VIRAL: "Carga Viral Desconhecida",
    SYMPTOM_NECROTIC: "Tecido Necrótico",
    SYMPTOM_CYTOKINE: "Tempestade de Citocina",
    SYMPTOM_FAILURE: "Falência de Órgãos",
    SYMPTOM_TOXICITY: "Toxicidade Sanguínea",
    SYMPTOM_DECAY: "Decaimento Celular",
    SYMPTOM_MUTATION: "Mutação Rápida",
    // Upgrades
    UP_MITOSIS_NAME: "MITOSE RÁPIDA",
    UP_MITOSIS_DESC: "+10% Cadência de Tiro",
    UP_MEMBRANE_NAME: "MEMBRANA DE TITÂNIO",
    UP_MEMBRANE_DESC: "+25% Vida Máx & Cura Total",
    UP_ENZYME_NAME: "HIPER ENZIMAS",
    UP_ENZYME_DESC: "+15% Dano",
    UP_MULTISHOT_NAME: "DIVISÃO ADAPTATIVA",
    UP_MULTISHOT_DESC: "+1 Projétil, -15% Dano",
    UP_ENERGY_NAME: "IMPULSO MITOCONDRIAL",
    UP_ENERGY_DESC: "Surto e Esquiva recarregam 15% mais rápido",
    UP_GIGA_NAME: "TEMPESTADE CITOCINA",
    UP_GIGA_DESC: "+2 Proj, +20% Dano, Cura Total",
    UP_ORBITAL_NAME: "NANO-GUARDIÕES",
    UP_ORBITAL_DESC: "Adiciona +1 Drone de Defesa Autônomo",
    UP_DASH_NAME: "RASTRO DE PLASMA",
    UP_DASH_DESC: "Dash causa 30 de Dano ao atravessar inimigos",
    UP_CRIT_NAME: "ÓPTICA DE PRECISÃO",
    UP_CRIT_DESC: "+10% Chance Crítica, +0.3x Dano Crítico",
    UP_THORNS_NAME: "CARAPAÇA DE ESPINHOS",
    UP_THORNS_DESC: "Causa 3 de Dano ao ser tocado",
    UP_LIFE_NAME: "CEPA VAMPÍRICA",
    UP_LIFE_DESC: "Abates críticos curam +1 Vida",
    UP_MAGNET_NAME: "CAMPO MAGNÉTICO",
    UP_MAGNET_DESC: "+20% Alcance do Ímã e Tamanho do Surto",
    // Achievements
    ACH_KILL_100_TITLE: "Dedetizador",
    ACH_KILL_100_DESC: "Elimine 100 patógenos.",
    ACH_KILL_1000_TITLE: "Esterilizador",
    ACH_KILL_1000_DESC: "Elimine 1.000 patógenos.",
    ACH_KILL_5000_TITLE: "Erradicador",
    ACH_KILL_5000_DESC: "Elimine 5.000 patógenos.",
    ACH_KILL_10000_TITLE: "Evento de Extinção",
    ACH_KILL_10000_DESC: "Elimine 10.000 patógenos.",
    ACH_BOSS_1_TITLE: "Anomalia Neutralizada",
    ACH_BOSS_1_DESC: "Derrote seu primeiro Boss.",
    ACH_BOSS_10_TITLE: "Matador de Titãs",
    ACH_BOSS_10_DESC: "Derrote 10 Bosses.",
    ACH_BOSS_50_TITLE: "Rei das Veias",
    ACH_BOSS_50_DESC: "Derrote 50 Bosses.",
    ACH_DASH_KILL_50_TITLE: "Atropelamento",
    ACH_DASH_KILL_50_DESC: "Mate 50 inimigos usando o dano do Dash.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Mate 100 inimigos com a explosão do Surto.",
    ACH_MINE_POP_20_TITLE: "Campo Minado",
    ACH_MINE_POP_20_DESC: "Detone 20 Bio-Minas.",
    ACH_BIOMASS_10K_TITLE: "Acumulador",
    ACH_BIOMASS_10K_DESC: "Colete um total de 10.000 de Biomassa.",
    ACH_WAVE_5_TITLE: "Sobrevivente",
    ACH_WAVE_5_DESC: "Chegue à Onda 5.",
    ACH_WAVE_10_TITLE: "Mergulho Profundo",
    ACH_WAVE_10_DESC: "Chegue à Onda 10 (Modo Infinito).",
    ACH_SCORE_50K_TITLE: "Recordista",
    ACH_SCORE_50K_DESC: "Alcance 50.000 pontos em uma partida.",
    ACH_COMBO_50_TITLE: "Estado de Fluxo",
    ACH_COMBO_50_DESC: "Alcance um Combo de 50x.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Alcance 200 de Vida Máxima em uma partida.",
    ACH_FIRE_RATE_MAX_TITLE: "Metralhadora",
    ACH_FIRE_RATE_MAX_DESC: "Maximize o upgrade de Cadência de Tiro.",
    ACH_PERFECT_WAVE_TITLE: "Intocável",
    ACH_PERFECT_WAVE_DESC: "Complete uma onda sem levar dano.",
    ACH_LOW_HP_SURVIVE_TITLE: "Viciado em Adrenalina",
    ACH_LOW_HP_SURVIVE_DESC: "Vença uma onda com < 20% de Vida.",
    ACH_CRIT_MASTER_TITLE: "Precisão Cirúrgica",
    ACH_CRIT_MASTER_DESC: "Acerte 1.000 Críticos.",
    ACH_UNLOCK_ALL_TITLE: "Perfeição Genética",
    ACH_UNLOCK_ALL_DESC: "Compre todos os tipos de upgrade pelo menos uma vez.",
    ACH_WIN_APEX_TITLE: "Predador Apex",
    ACH_WIN_APEX_DESC: "Complete a Onda 5 na dificuldade APEX.",
    ACH_DIE_10_TITLE: "Tentativa e Erro",
    ACH_DIE_10_DESC: "Morra 10 vezes.",
    ACH_AFK_TITLE: "Estátua",
    ACH_AFK_DESC: "Fique parado por 10 segundos em combate.",
    ACH_PACIFIST_TITLE: "Pacifista",
    ACH_PACIFIST_DESC: "Sobreviva 30 segundos sem atirar.",
    ACH_OVERKILL_TITLE: "Exagero",
    ACH_OVERKILL_DESC: "Cause mais de 500 de dano em um único hit.",
    ACH_RICH_TITLE: "Magnata",
    ACH_RICH_DESC: "Tenha 3.000 de Biomassa ao mesmo tempo.",
    ACH_PLAY_TIME_1H_TITLE: "Estagiário",
    ACH_PLAY_TIME_1H_DESC: "Jogue por 1 hora (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Especialista",
    ACH_PLAY_TIME_5H_DESC: "Jogue por 5 horas (Total).",
    ACH_ALL_TITLE: "O VÍRUS APEX",
    ACH_ALL_DESC: "Desbloqueie todas as outras conquistas."
  },
  ES: {
    TITLE_MAIN: "VITAL",
    TITLE_SUB: "RUSH",
    START: "INYECTAR",
    SETTINGS: "CONFIG",
    CONTROLS: "CONTROLES",
    MANUAL: "BASE DE DATOS",
    CREDITS: "CRÉDITOS",
    LANG: "IDIOMA",
    BACK: "VOLVER",
    PAUSED: "SISTEMA PAUSADO",
    RESUME: "REANUDAR",
    ABORT: "ABORTAR MISIÓN",
    GAME_OVER: "PACIENTE PERDIDO",
    RETRY: "SIGUIENTE PACIENTE",
    WAVE: "OLEADA",
    SCORE: "PUNTUACIÓN",
    CLEARED: "ESTABILIZADO",
    NEXT: "PRÓXIMO SECTOR",
    MUTATION: "BIO-LABORATORIO",
    SELECT_DNA: "GASTAR BIOMASA PARA EVOLUCIONAR",
    SURGE_READY: "SURGE",
    DEPLOY: "DESPLEGAR",
    BRIEFING: "EXPEDIENTE",
    BOSS_WARNING: "ANOMALÍA DETECTADA",
    OPEN_SHOP: "ABRIR BIO-LAB",
    PURCHASE: "EVOLUCIONAR",
    COST: "COSTO",
    MAXED: "MÁX",
    COMBO: "COMBO",
    DASH: "ESQUIVA",
    DIFFICULTY: "NIVEL DE RIESGO",
    PATIENT: "SUJETO",
    STRAIN: "CEPA",
    BIOMASS_AVAIL: "BIOMASA DISPONIBLE",
    AUDIO_LINK: "ENLACE DE AUDIO",
    STATUS_TERM: "ESTADO: TERMINADO",
    INTEGRITY: "INTEGRIDAD",
    ADRENALINE: "ADRENALINA ACTIVA",
    LOADOUT: "GENOMA ACTIVO",
    ACHIEVEMENTS: "LOGROS",
    ACH_LOCKED: "BLOQUEADO",
    ACH_PROGRESS: "PROGRESO",
    ACH_PLATINUM_MSG: "ANULACIÓN DEL SISTEMA: MODO APEX ACTIVADO. VISUALES EVOLUCIONADOS.",
    DIFF_TRIAGE: "TRIAJE",
    DIFF_RESIDENT: "RESIDENTE",
    DIFF_SPECIALIST: "ESPECIALISTA",
    DIFF_APEX: "APEX",
    CTRL_MOVE: "MOVIMIENTO",
    CTRL_MOVE_DESC: "WASD / FLECHAS / JOYSTICK TÁCTIL",
    CTRL_DASH: "ESQUIVA",
    CTRL_DASH_DESC: "SHIFT / E / BOTÓN TÁCTIL",
    CTRL_SURGE: "SURGE DEFINITIVA",
    CTRL_SURGE_DESC: "ESPACIO / BOTÓN TÁCTIL",
    CTRL_NOTE: "DISPARO AUTOMÁTICO SIEMPRE ACTIVO",
    MANUAL_HOSTILES: "HOSTILES",
    MANUAL_STRAINS: "CEPAS VIRALES",
    MANUAL_MECHANICS: "MECÁNICA DE BATALLA",
    MANUAL_BAC_DESC: "Patógeno estándar. Movimiento común y predecible.",
    MANUAL_VIR_DESC: "Atacante rápido. Poca vida, pero ataca en enjambre.",
    MANUAL_PAR_DESC: "Tanque pesado. Lento, mucha vida, absorve daño.",
    MANUAL_BOSS_DESC: "Anomalia masiva. Requiere potencia de fuego extrema.",
    MANUAL_MECH_DASH_TITLE: "Evasión (Dash)",
    MANUAL_MECH_DASH_DESC: "Otorga invulnerabilidad momentánea. Úsalo para atravesar enemigos.",
    MANUAL_MECH_SURGE_TITLE: "Sistema Surge",
    MANUAL_MECH_SURGE_DESC: "Empuja enemigos y MAGNETIZA toda la biomasa al instante.",
    MANUAL_MECH_COMBO_TITLE: "Cadena de Combo",
    MANUAL_MECH_COMBO_DESC: "Mata rápido para aumentar multiplicador. Recibir daño reinicia el combo.",
    STRAIN_STANDARD: "PATÓGENO ESTÁNDAR",
    STRAIN_SWARM: "ENJAMBRE MASIVO",
    STRAIN_TITAN: "TITÁN BLINDADO",
    STRAIN_VOLATILE: "MUTACIÓN VOLÁTIL",
    STRAIN_STD_DESC: "Parámetros de infección basales.",
    STRAIN_SWM_DESC: "Alto número de enemigos, menos vida individual.",
    STRAIN_TTN_DESC: "Enemigos con +100% Vida. Spawns más lentos.",
    STRAIN_VOL_DESC: "Enemigos mueven 30% más rápido. Alta agresión.",
    ROLE_DEV: "DESARROLLO",
    ROLE_DIR: "DIRECTOR",
    DEV_STUDIO: "ESTÚDIO CRIA",
    DIRECTOR: "PAULO GABRIEL DE L. S.",
    SYMPTOM_SEPTIC: "Choque Séptico",
    SYMPTOM_VIRAL: "Carga Viral Desconocida",
    SYMPTOM_NECROTIC: "Tejido Necrótico",
    SYMPTOM_CYTOKINE: "Tormenta de Citocinas",
    SYMPTOM_FAILURE: "Fallo Orgánico",
    SYMPTOM_TOXICITY: "Toxicidad Sanguínea",
    SYMPTOM_DECAY: "Decadencia Celular",
    SYMPTOM_MUTATION: "Mutación Rápida",
    // Upgrades
    UP_MITOSIS_NAME: "MITOSIS RÁPIDA",
    UP_MITOSIS_DESC: "+10% Cadencia de Tiro",
    UP_MEMBRANE_NAME: "MEMBRANA DE TITANIO",
    UP_MEMBRANE_DESC: "+25% Vida Máx & Cura Total",
    UP_ENZYME_NAME: "HIPER ENZIMAS",
    UP_ENZYME_DESC: "+15% Daño",
    UP_MULTISHOT_NAME: "DIVISIÓN ADAPTATIVA",
    UP_MULTISHOT_DESC: "+1 Proyectil, -15% Daño",
    UP_ENERGY_NAME: "IMPULSO MITOCONDRIAL",
    UP_ENERGY_DESC: "Surge y Esquiva recarga 15% más rápido",
    UP_GIGA_NAME: "TORMENTA CITOCINA",
    UP_GIGA_DESC: "+2 Proy, +20% Daño, Cura Total",
    UP_ORBITAL_NAME: "NANO-GUARDIANES",
    UP_ORBITAL_DESC: "Añade +1 Dron de Defensa Autónomo",
    UP_DASH_NAME: "RASTRO DE PLASMA",
    UP_DASH_DESC: "Dash causa 30 de Daño al atravesar enemigos",
    UP_CRIT_NAME: "ÓPTICA DE PRECISIÓN",
    UP_CRIT_DESC: "+10% Prob. Crítica, +0.3x Daño Crítico",
    UP_THORNS_NAME: "CAPARAZÓN DE ESPINAS",
    UP_THORNS_DESC: "Causa 3 de Daño al ser tocado",
    UP_LIFE_NAME: "CEPA VAMPÍRICA",
    UP_LIFE_DESC: "Bajas críticas curan +1 Vida",
    UP_MAGNET_NAME: "CAMPO MAGNÉTICO",
    UP_MAGNET_DESC: "+20% Rango de Imán y Tamaño de Surge",
    // Achievements
    ACH_KILL_100_TITLE: "Limpiador",
    ACH_KILL_100_DESC: "Elimina 100 patógenos.",
    ACH_KILL_1000_TITLE: "Esterilizador",
    ACH_KILL_1000_DESC: "Elimina 1.000 patógenos.",
    ACH_KILL_5000_TITLE: "Erradicador",
    ACH_KILL_5000_DESC: "Elimina 5.000 patógenos.",
    ACH_KILL_10000_TITLE: "Evento de Extinción",
    ACH_KILL_10000_DESC: "Elimina 10.000 patógenos.",
    ACH_BOSS_1_TITLE: "Anomalía Neutralizada",
    ACH_BOSS_1_DESC: "Derrota a tu primer Jefe.",
    ACH_BOSS_10_TITLE: "Asesino de Titanes",
    ACH_BOSS_10_DESC: "Derrota a 10 Jefes.",
    ACH_BOSS_50_TITLE: "Rey de las Venas",
    ACH_BOSS_50_DESC: "Derrota a 50 Jefes.",
    ACH_DASH_KILL_50_TITLE: "Atropello",
    ACH_DASH_KILL_50_DESC: "Mata 50 enemigos usando el daño de Dash.",
    ACH_SURGE_KILL_100_TITLE: "Tsunami",
    ACH_SURGE_KILL_100_DESC: "Mata 100 enemigos con la explosión de Surge.",
    ACH_MINE_POP_20_TITLE: "Buscaminas",
    ACH_MINE_POP_20_DESC: "Detona 20 Bio-Minas.",
    ACH_BIOMASS_10K_TITLE: "Acaparador",
    ACH_BIOMASS_10K_DESC: "Recolecta un total de 10.000 de Biomasa.",
    ACH_WAVE_5_TITLE: "Sobreviviente",
    ACH_WAVE_5_DESC: "Llega a la Oleada 5.",
    ACH_WAVE_10_TITLE: "Inmersión Profunda",
    ACH_WAVE_10_DESC: "Llega a la Oleada 10 (Modo Infinito).",
    ACH_SCORE_50K_TITLE: "Puntuación Máxima",
    ACH_SCORE_50K_DESC: "Alcanza 50.000 puntos en una partida.",
    ACH_COMBO_50_TITLE: "Estado de Flujo",
    ACH_COMBO_50_DESC: "Alcanza un Combo de 50x.",
    ACH_MAX_HP_200_TITLE: "Juggernaut",
    ACH_MAX_HP_200_DESC: "Alcanza 200 de Vida Máxima en una partida.",
    ACH_FIRE_RATE_MAX_TITLE: "Ametralladora",
    ACH_FIRE_RATE_MAX_DESC: "Maximiza la mejora de Cadencia de Tiro.",
    ACH_PERFECT_WAVE_TITLE: "Intocable",
    ACH_PERFECT_WAVE_DESC: "Completa una oleada sin recibir daño.",
    ACH_LOW_HP_SURVIVE_TITLE: "Adicto a la Adrenalina",
    ACH_LOW_HP_SURVIVE_DESC: "Gana una oleada con < 20% de Vida.",
    ACH_CRIT_MASTER_TITLE: "Precisión Quirúrgica",
    ACH_CRIT_MASTER_DESC: "Acierta 1.000 Críticos.",
    ACH_UNLOCK_ALL_TITLE: "Perfección Genética",
    ACH_UNLOCK_ALL_DESC: "Compra todos los tipos de mejora al menos una vez.",
    ACH_WIN_APEX_TITLE: "Depredador Apex",
    ACH_WIN_APEX_DESC: "Completa la Oleada 5 en dificultad APEX.",
    ACH_DIE_10_TITLE: "Prueba y Error",
    ACH_DIE_10_DESC: "Muere 10 veces.",
    ACH_AFK_TITLE: "Estatua",
    ACH_AFK_DESC: "Quédate quieto durante 10 segundos en combate.",
    ACH_PACIFIST_TITLE: "Pacifista",
    ACH_PACIFIST_DESC: "Sobrevive 30 segundos sin disparar.",
    ACH_OVERKILL_TITLE: "Exagerado",
    ACH_OVERKILL_DESC: "Inflige más de 500 de daño en un solo golpe.",
    ACH_RICH_TITLE: "Magnate",
    ACH_RICH_DESC: "Ten 3.000 de Biomasa al mismo tiempo.",
    ACH_PLAY_TIME_1H_TITLE: "Becario",
    ACH_PLAY_TIME_1H_DESC: "Juega durante 1 hora (Total).",
    ACH_PLAY_TIME_5H_TITLE: "Especialista",
    ACH_PLAY_TIME_5H_DESC: "Juega durante 5 horas (Total).",
    ACH_ALL_TITLE: "EL VIRUS APEX",
    ACH_ALL_DESC: "Desbloquea todos los demás logros."
  }
};

// Configuração das Ondas.
// Ajustado para o modo "Pesadelo". Spawns mais rápidos desde o começo.
export const WAVES: WaveConfig[] = [
  { waveNumber: 1, duration: 40, spawnRate: 600, enemyTypes: [EntityType.BACTERIA], flowSpeed: -0.6, hasBoss: false },
  { waveNumber: 2, duration: 55, spawnRate: 500, enemyTypes: [EntityType.BACTERIA, EntityType.VIRUS], flowSpeed: -0.8, hasBoss: false },
  { waveNumber: 3, duration: 60, spawnRate: 400, enemyTypes: [EntityType.BACTERIA, EntityType.VIRUS], flowSpeed: -1.0, hasBoss: true }, // Boss de treino
  { waveNumber: 4, duration: 80, spawnRate: 350, enemyTypes: [EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.3, hasBoss: false },
  { waveNumber: 5, duration: 999, spawnRate: 150, enemyTypes: [EntityType.BACTERIA, EntityType.VIRUS, EntityType.PARASITE], flowSpeed: -1.8, hasBoss: true }, // Spam insano
];

// O "Shopping" do jogo.
// Inflação aplicada. Tudo custa o olho da cara.
export const UPGRADES: Upgrade[] = [
  {
    id: 'mitosis',
    nameKey: 'UP_MITOSIS_NAME',
    descKey: 'UP_MITOSIS_DESC',
    rarity: 'COMMON',
    baseCost: 200,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, fireRate: Math.max(100, s.fireRate * 0.90) })
  },
  {
    id: 'enzyme',
    nameKey: 'UP_ENZYME_NAME',
    descKey: 'UP_ENZYME_DESC',
    rarity: 'RARE',
    baseCost: 350,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, damage: s.damage * 1.15 }) // Nerf no scaling (25% -> 15%)
  },
  {
    id: 'membrane',
    nameKey: 'UP_MEMBRANE_NAME',
    descKey: 'UP_MEMBRANE_DESC',
    rarity: 'COMMON',
    baseCost: 250,
    costMultiplier: 1.6,
    level: 0,
    maxLevel: 10,
    apply: (s) => ({ ...s, maxHealth: Math.floor(s.maxHealth * 1.25), health: Math.floor(s.maxHealth * 1.25) })
  },
  {
    id: 'multishot',
    nameKey: 'UP_MULTISHOT_NAME',
    descKey: 'UP_MULTISHOT_DESC',
    rarity: 'EPIC',
    baseCost: 1000,
    costMultiplier: 2.5,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, bulletCount: s.bulletCount + 1, damage: s.damage * 0.85 })
  },
  {
    id: 'orbitals',
    nameKey: 'UP_ORBITAL_NAME',
    descKey: 'UP_ORBITAL_DESC',
    rarity: 'EPIC',
    baseCost: 1500, // Ficou caro demais pra comprar no começo
    costMultiplier: 3.0,
    level: 0,
    maxLevel: 4,
    apply: (s) => ({ ...s, orbitals: s.orbitals + 1 })
  },
  {
    id: 'crit',
    nameKey: 'UP_CRIT_NAME',
    descKey: 'UP_CRIT_DESC',
    rarity: 'RARE',
    baseCost: 500,
    costMultiplier: 2.0,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, critChance: s.critChance + 0.10, critMultiplier: s.critMultiplier + 0.3 })
  },
  {
    id: 'dash_dmg',
    nameKey: 'UP_DASH_NAME',
    descKey: 'UP_DASH_DESC',
    rarity: 'COMMON',
    baseCost: 300,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, dashDamage: s.dashDamage + 30 })
  },
  {
    id: 'thorns',
    nameKey: 'UP_THORNS_NAME',
    descKey: 'UP_THORNS_DESC',
    rarity: 'COMMON',
    baseCost: 400,
    costMultiplier: 2.0,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, thorns: s.thorns + 3 }) // Nerf Brutal: 10 -> 3. Tentar AFK agora = morte.
  },
  {
    id: 'lifesteal',
    nameKey: 'UP_LIFE_NAME',
    descKey: 'UP_LIFE_DESC',
    rarity: 'LEGENDARY',
    baseCost: 2000,
    costMultiplier: 3.5,
    level: 0,
    maxLevel: 3,
    apply: (s) => ({ ...s, lifesteal: s.lifesteal + 0.05 })
  },
  {
    id: 'magnet',
    nameKey: 'UP_MAGNET_NAME',
    descKey: 'UP_MAGNET_DESC',
    rarity: 'COMMON',
    baseCost: 200,
    costMultiplier: 1.5,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, magnetRadius: s.magnetRadius * 1.2, surgeRadiusMult: s.surgeRadiusMult * 1.1 })
  },
  {
    id: 'energy_core',
    nameKey: 'UP_ENERGY_NAME',
    descKey: 'UP_ENERGY_DESC',
    rarity: 'RARE',
    baseCost: 400,
    costMultiplier: 1.8,
    level: 0,
    maxLevel: 5,
    apply: (s) => ({ ...s, maxEnergy: Math.max(50, s.maxEnergy * 0.85), dashCooldown: Math.max(400, s.dashCooldown * 0.85) })
  },
  {
    id: 'giga_blast',
    nameKey: 'UP_GIGA_NAME',
    descKey: 'UP_GIGA_DESC',
    rarity: 'LEGENDARY',
    baseCost: 2500,
    costMultiplier: 3.0,
    level: 0,
    maxLevel: 3,
    apply: (s) => ({ ...s, bulletCount: s.bulletCount + 2, damage: s.damage * 1.2, health: s.maxHealth })
  }
];